import {test} from 'node:test';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';import {buildSync} from 'esbuild';
const build=buildSync({entryPoints:['src/encar-server.js'],bundle:true,platform:'node',format:'esm',write:false});
const {encarRequest}=await import('data:text/javascript;base64,'+Buffer.from(build.outputFiles[0].text).toString('base64'));
function db(){const sql=new DatabaseSync(':memory:');sql.exec('CREATE TABLE app_meta(key TEXT PRIMARY KEY,value TEXT NOT NULL)');return {prepare(s){let args=[];return {bind(...v){args=v;return this},async first(){return sql.prepare(s).get(...args)},async all(){return {results:sql.prepare(s).all(...args)}},async run(){return {meta:sql.prepare(s).run(...args)}}}}};}
const req=(body)=>new Request('https://crm.example/api/encar/quotes',body?{method:'POST',body:JSON.stringify(body)}:{});
const actor={name:'Тест'};
test('cloud quotes: save, reload, revision update, reject stale write',async()=>{const env={DB:db()};const first=await encarRequest(req({brand:'BMW',model:'740d',tableId:'5',eur:1}),env,actor);assert.equal(first.status,200);const q=await first.json();assert.equal(q.eur,80209);const list=await (await encarRequest(req(),env,actor)).json();assert.equal(list.quotes[0].id,q.id);assert.equal((await encarRequest(req({...q,manualTpo:100}),env,actor)).status,200);assert.equal((await encarRequest(req(q),env,actor)).status,409);});
test('unknown TPO row rejected without writing',async()=>{const env={DB:db()};assert.equal((await encarRequest(req({brand:'BMW',model:'740d',tableId:'invalid'}),env,actor)).status,400);const list=await (await encarRequest(req(),env,actor)).json();assert.equal(list.quotes.length,0);});
test('new formula round-trips through cloud and recalculates from authoritative EUR row',async()=>{const {emptyQuote}=await import('../src/encar.js');const env={DB:db()};const draft={...emptyQuote(),brand:'BMW',model:'X5',tableId:'129',eur:1,krw:100000000,krwPerUsd:1000,eurUsd:1.1,usdRub:90,engine:2993,powerHp:298,powertrain:'ice',utilAge:'new'};const response=await encarRequest(req(draft),env,actor);assert.equal(response.status,200);const q=await response.json();assert.equal(q.eur,32000);assert.equal(q.result.tpo,16896);assert.equal(q.result.rub,13822412.8);const loaded=(await (await encarRequest(req(),env,actor)).json()).quotes[0];assert.equal(loaded.powerHp,298);assert.equal(loaded.koreaKrw,6000000);const update=await (await encarRequest(req({...loaded,eurUsd:1.2}),env,actor)).json();assert.equal(update.result.tpo,18432);assert.notEqual(update.result.rub,q.result.rub);});
test('power catalog persists edits with stale-write protection',async()=>{const env={DB:db()};const get=()=>new Request('https://crm.example/api/encar/power');const post=b=>new Request('https://crm.example/api/encar/power',{method:'POST',body:JSON.stringify(b)});const seed=(await (await encarRequest(get(),env,actor)).json()).rows[0];const saved=await (await encarRequest(post({...seed,powerHp:299}),env,actor)).json();assert.equal(saved.powerHp,299);const rows=(await (await encarRequest(get(),env,actor)).json()).rows;assert.equal(rows.length,1);assert.equal(rows[0].powerHp,299);assert.equal((await encarRequest(post({...seed,powerHp:300}),env,actor)).status,400);const changed=await (await encarRequest(post({...saved,powerHp:300,expectedUpdatedAt:saved.updatedAt}),env,actor)).json();assert.equal(changed.powerHp,300);});
