import {test} from 'node:test';import assert from 'node:assert/strict';import {listingURL,parseListing,fetchListing,tpoEngine,matchTpo,listingVin} from '../src/encar-import.js';
const fixture={vehicleId:42641294,category:{manufacturerEnglishName:'BMW',modelEnglishName:'740d',formYear:2025},spec:{displacement:3000,mileage:23000},advertisement:{price:11590}};
test('source price in ten thousand won and specs',()=>{const {quote}=parseListing(fixture,'42641294','https://fem.encar.com/cars/detail/42641294');assert.equal(quote.krw,115900000);assert.equal(quote.year,'2025');assert.equal(quote.mileage,23000);});
test('page preloaded JSON parses without executing scripts',()=>{const p=parseListing('window.__PRELOADED_STATE__ = '+JSON.stringify({cars:{base:fixture}})+'; throw Error()', '42641294','');assert.equal(p.quote.brand,'BMW');});
test('URLs reject SSRF, credentials, port and foreign host',()=>{for(const u of ['http://fem.encar.com/cars/detail/42641294','https://user@fem.encar.com/cars/detail/42641294','https://fem.encar.com:123/cars/detail/42641294','https://127.0.0.1/cars/detail/42641294','https://fem.encar.com.evil.test/cars/detail/42641294'])assert.throws(()=>listingURL(u));});
test('fetch matches only an unambiguous tariff and preserves unknown fees',async()=>{const r=await fetchListing('https://fem.encar.com/cars/detail/42641294?foo=bar',[{id:'1',brand:'BMW',model:'740d',engine:'3000',year:'2025',eur:30000}],async()=>new Response(JSON.stringify(fixture)));assert.equal(r.quote.eur,30000);assert.equal(r.quote.utilRub,'');});
test('Encar outage yields a useful error, not a made-up quote',async()=>{await assert.rejects(fetchListing('https://fem.encar.com/cars/detail/42641294',[],async()=>new Response('blocked',{status:403})),/Не удалось получить/);});

test('TPO engine rounds upward; litres and cc supported; unknown and ranges excluded',()=>{for(const [input,expected] of [[2998,'3000'],[2985,'3000'],[3000,'3000'],[3001,'3100'],[1998,'2000'],['3','3000'],['3,0','3000'],['',null],[0,null],['до 4100',null]])assert.equal(tpoEngine(input),expected);});
test('2998 matches tariff 3000 without changing actual displacement',async()=>{const row={id:'1',brand:'BMW',model:'740d',engine:'3000',year:'2025',eur:30000};const data={...fixture,spec:{...fixture.spec,displacement:2998}};const r=await fetchListing('https://fem.encar.com/cars/detail/42641294',[row],async()=>new Response(JSON.stringify(data)));assert.equal(r.quote.tableId,'1');assert.equal(r.quote.engine,'2998');assert.equal(matchTpo(r.quote,[],[row,{...row,id:'2'}]),null);assert.equal(matchTpo({...r.quote,year:'2024'},[],[row]),null);});

test('VIN accepts only full VIN, rejects plates and masked values',()=>{assert.equal(listingVin({vehicleNo:'WBA21EJ04SCV37213'}),'WBA21EJ04SCV37213');assert.equal(listingVin({vin:'***',vehicleNo:'123가4567'}),'');assert.equal(listingVin({vin:'hidden',spec:{vin:'WBA21EJ04SCV37213'}}),'WBA21EJ04SCV37213');});
test('missing API VIN is supplemented from page without changing API price',async()=>{const page={cars:{base:{...fixture,vehicleNo:'WBA21EJ04SCV37213',advertisement:{price:1}}}};let calls=0;const result=await fetchListing('https://fem.encar.com/cars/detail/42641294',[],async()=>new Response(++calls===1?JSON.stringify(fixture):'window.__PRELOADED_STATE__='+JSON.stringify(page)));assert.equal(calls,2);assert.equal(result.quote.vin,'WBA21EJ04SCV37213');assert.equal(result.quote.krw,115900000);});

test('BMW X5 generation and trim are separate, actual tariff 2024/3000 is found',async()=>{const {readFileSync}=await import('node:fs');const table=JSON.parse(readFileSync(new URL('../src/encar-table.json',import.meta.url)));const data={...fixture,category:{manufacturerEnglishName:'BMW',modelEnglishName:'X5 (G05)',gradeEnglishName:'xDrive 30d xLine',formYear:2024},spec:{displacement:2993,mileage:19047}};const r=await fetchListing('https://fem.encar.com/cars/detail/42641294',table,async()=>new Response(JSON.stringify(data)));assert.equal(r.quote.model,'X5');assert.equal(r.quote.trim,'xDrive 30d xLine');assert.equal(r.quote.engine,'2993');assert.equal(r.quote.tableId,'129');assert.equal(r.quote.eur,32000);});

test('power import accepts explicit PS/kW, rejects unknown units and rpm text',async()=>{const {listingPower}=await import('../src/encar-import.js');assert.equal(listingPower({maxPower:'298 PS'}).powerHp,298);assert.ok(Math.abs(listingPower({powerKw:220}).powerHp-299.116)<.01);assert.equal(listingPower({maxPower:298}).powerHp,'');assert.equal(listingPower({maxPower:'298/4000 rpm'}).powerHp,'');});
