import React,{useState,useEffect,useRef} from 'react';
import AdDraftDialog from './AdDraftDialog.jsx';
import {Megaphone,Sparkles,Search,Download,Save,Loader2,ArrowUp,ArrowDown,ExternalLink,CheckCircle2,AlertCircle} from 'lucide-react';
import {AVITO_STATES,AVITO_GROUPS,AVITO_LABELS,AVITO_TEMPLATE,AVITO_DOCS,CAR_LINKS,NUMERIC_FIELDS,avitoFields,avitoPhotos,avitoCheck} from './avito.js';
import './avito.css';
import {carHash} from './car-navigation.js';
import './telegram.css';
const money=n=>n===null||n===undefined?'Недостаточно данных':new Intl.NumberFormat('ru-RU').format(n)+' ₽';
function initial(c){return {state:c.avito?.state||'draft',title:c.avito?.title||'',listingUrl:c.avito?.listingUrl||'',fields:avitoFields(c),photoIds:c.avito?.photoIds||[],selected:c.avito?.selected||false,catalogConfirmed:c.avito?.catalogConfirmed||false};}
export default function Avito({car,cars,api,onSaved,readOnly,isOwner}){
 const [aiError,setAIError]=useState(''),[applied,setApplied]=useState(false);
 const [v,setV]=useState(()=>initial(car)),[busy,setBusy]=useState(''),[error,setError]=useState(''),[checkVisible,setCheckVisible]=useState(false),[proposal,setProposal]=useState(null),[market,setMarket]=useState(null),[bundle,setBundle]=useState(null),[aiEnabled,setAI]=useState(false);
 const alive=useRef(true),lock=useRef(false),checkRef=useRef();
 useEffect(()=>{alive.current=true;api('/avito/config').then(r=>alive.current&&setAI(r.aiEnabled)).catch(()=>{});return()=>{alive.current=false;};},[]);
 useEffect(()=>()=>{if(bundle){URL.revokeObjectURL(bundle.xlsx);URL.revokeObjectURL(bundle.photos);}},[bundle]);
 const dirty=JSON.stringify(v)!==JSON.stringify(initial(car)),photos=avitoPhotos(car),check=avitoCheck(car,v),selectedCars=cars.filter(c=>c.avito?.selected),disabled=readOnly||!!busy;
 const change=(k,value)=>{setBundle(null);setV(x=>({...x,[k]:value,...(k==='state'&&value==='sold'?{selected:false}:{})}));};
 const field=(k,value)=>{setBundle(null);setV(x=>({...x,fields:{...x.fields,[k]:value},catalogConfirmed:['Make','Model','GenerationId','ModificationId','ComplectationId'].includes(k)?false:x.catalogConfirmed}));};
 async function run(label,fn,onError){if(lock.current)return;lock.current=true;setBusy(label);setError('');try{await fn();}catch(e){if(alive.current){if(onError)onError(e.message);else setError(e.message);}}finally{lock.current=false;if(alive.current)setBusy('');}}
 async function save(e){e.preventDefault();await run('Сохраняю…',async()=>{const saved=await api('/cars/'+car.id+'/avito',{method:'PATCH',body:{...v,revision:car.revision}});onSaved(saved);});}
 async function ai(kind){setAIError('');setApplied(false);await run(kind==='market'?'Ищу сопоставимые предложения…':'Готовлю текст…',async()=>{const result=await api('/cars/'+car.id+'/avito/'+kind,{method:'POST',body:{...v,revision:car.revision}});if(alive.current)(kind==='market'?setMarket:setProposal)(result);},setAIError);}
 async function prepare(all){if(dirty){setError('Сначала сохраните изменения объявления.');return;}setCheckVisible(true);if(!check.ready&&!all){checkRef.current?.scrollIntoView({block:'center',behavior:'smooth'});return;}
  await run('Проверяю карточки…',async()=>{const refs=(all?selectedCars:[car]).map(c=>({id:c.id,revision:c.revision}));const prepared=await api('/avito/prepare',{method:'POST',body:{cars:refs}});const {buildAvitoBundle}=await import('./avito-export.js');const result=await buildAvitoBundle(prepared,()=>api('/avito/verify',{method:'POST',body:{cars:refs}}),text=>alive.current&&setBusy(text));if(alive.current)setBundle({xlsx:URL.createObjectURL(result.xlsx),photos:URL.createObjectURL(result.photos),count:result.count});});
 }
 function move(id,d){const ids=[...v.photoIds],i=ids.indexOf(id),j=i+d;if(i<0||j<0||j>=ids.length)return;[ids[i],ids[j]]=[ids[j],ids[i]];change('photoIds',ids);}
 async function boom(enabled){await run('Обновляю Бум Авто…',async()=>onSaved(await api('/cars/'+car.id+'/publication',{method:'PATCH',body:{...car.publication,revision:car.revision,enabled,autoPhotos:car.publication?.autoPhotos??true,photoIds:car.publication?.photoIds||[],description:car.publication?.description||''}})));}
 const renderField=k=>{const error=checkVisible&&check.errors.find(e=>e.field===k),required=AVITO_TEMPLATE.fields.find(f=>f.key===k)?.required,choices=AVITO_TEMPLATE.choices[k];return <label className={'field '+(error?'avito-invalid':'')} key={k} htmlFor={'avito-'+k}><span>{AVITO_LABELS[k]||k}{required&&<em title="Нужно для выгрузки"> *</em>}{CAR_LINKS[k]&&<small>В карточке авто</small>}</span>{choices?<select id={'avito-'+k} value={v.fields[k]??''} onChange={e=>field(k,e.target.value)}><option value="">Не указано</option>{v.fields[k]&&!choices.includes(String(v.fields[k]))&&<option value={v.fields[k]}>{v.fields[k]} — проверьте</option>}{choices.map(x=><option key={x}>{x}</option>)}</select>:<input id={'avito-'+k} type={NUMERIC_FIELDS.has(k)?'number':k==='ContactPhone'?'tel':'text'} step={['EngineSize'].includes(k)?'0.1':'1'} min={NUMERIC_FIELDS.has(k)?0:undefined} maxLength={1000} value={v.fields[k]??''} onChange={e=>field(k,e.target.value)} placeholder={['GenerationId','ModificationId','ComplectationId'].includes(k)?'Из каталога Авито':undefined}/>} {error&&<small className="avito-field-error">{error.message}</small>}</label>;};
 return <div className="avito-module">
  <section className="panel avito-heading"><div><div className="avito-eyebrow"><Megaphone size={18}/> АВИТО</div><h2>Подготовка объявления</h2><p>Сохраняйте черновик на любом этапе. Обязательные поля проверяются перед выгрузкой.</p></div><span className={'avito-state '+v.state}>{AVITO_STATES.find(x=>x[0]===v.state)?.[1]}</span></section>
  <form onSubmit={save} className="avito-form"><fieldset disabled={disabled}>
   <section className="panel"><div className="avito-channel-grid"><label><input type="checkbox" checked={!!car.publication?.enabled} disabled={!isOwner||dirty||disabled} onChange={e=>boom(e.target.checked)}/><span>Бум Авто<small>{dirty?'Сначала сохраните черновик':'Показывать на сайте'}</small></span></label><label><input type="checkbox" checked={v.selected} onChange={e=>change('selected',e.target.checked)}/><span>Авито<small>Включить в файл выгрузки</small></span></label><a className="telegram-channel-link" href={'#'+carHash(car.id,'telegram')} onClick={e=>{if(dirty){e.preventDefault();setError('Сначала сохраните изменения Авито.');}}}><ExternalLink size={18}/><span>Telegram<small>Подготовить пост</small></span></a><label className="avito-not-connected"><input type="checkbox" disabled/><span>Instagram<small>Не подключён</small></span></label></div></section>
   <section className="panel"><div className="avito-form-grid"><label className="field"><span>Статус учёта объявления</span><select value={v.state} onChange={e=>change('state',e.target.value)}>{AVITO_STATES.map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label><label className="field"><span>Ссылка на объявление</span><input value={v.listingUrl} onChange={e=>change('listingUrl',e.target.value)} placeholder="https://www.avito.ru/…" maxLength={1000}/></label></div><p className="avito-note">Статус отмечается вручную. Подготовка файла не публикует объявление и не снимает его с Авито.</p></section>
   <section className="panel"><div className="panel-title"><h3>Текст и цена</h3><button type="button" className="btn" disabled={!aiEnabled||disabled} onClick={()=>ai('generate')}>{busy==='Готовлю текст…'?<Loader2 size={17} className="spin"/>:<Sparkles size={17}/>} {busy==='Готовлю текст…'?'Готовлю текст…':'Создать объявление Авито'}</button></div>{aiError&&<p className="error ad-generation-error" role="alert">{aiError}</p>}{applied&&<p className="ad-generation-applied" role="status">Текст добавлен в форму. Сохраните черновик.</p>}<label className="field"><span>Заголовок для предпросмотра</span><input value={v.title} onChange={e=>change('title',e.target.value)} maxLength={200}/></label><p className="avito-note">В этой категории Авито формирует заголовок из характеристик. Отдельного поля Title в шаблоне нет.</p><label className="field"><span>Описание *</span><textarea id="avito-Description" rows={8} value={v.fields.Description||''} onChange={e=>field('Description',e.target.value)} maxLength={10000}/></label><div className="avito-price-row">{renderField('Price')}<button type="button" className="btn" disabled={!aiEnabled||disabled} onClick={()=>ai('market')}><Search size={17}/> Проверить цену рынка</button></div><p className="avito-note">Цена единая с карточкой автомобиля. AI использует подключённый OpenAI API и оплачивается с его баланса. Паспортные данные и себестоимость не передаются.</p>{!aiEnabled&&<p className="avito-note">AI недоступен без подключённого OpenAI. Черновик и выгрузка работают независимо.</p>}</section>
   {AVITO_GROUPS.map(([title,keys],i)=><details className="panel avito-group" open={i<3} key={title}><summary>{title}</summary><div className="avito-form-grid">{keys.map(renderField)}</div>{i===2&&<div className="avito-catalog-note"><p>В исходном шаблоне нет заполненного каталога моделей и модификаций. Укажите официальные значения и ID из Авито — CRM не подбирает их наугад.</p><a href={AVITO_DOCS} target="_blank" rel="noreferrer">Открыть требования Авито <ExternalLink size={14}/></a><label><input type="checkbox" checked={v.catalogConfirmed} onChange={e=>change('catalogConfirmed',e.target.checked)}/> Марка, модель, поколение и модификация сверены с Авито</label></div>}</details>)}
   <section className="panel"><div className="panel-title"><h3>Фото объявления · {v.photoIds.length}</h3><button type="button" className="text-btn" onClick={()=>change('photoIds',photos.slice(0,50).map(f=>f.id))} disabled={!photos.length}>Выбрать все</button></div><p className="avito-note">Первое выбранное фото — обложка Авито. Порядок фото в CRM не меняется. WEBP преобразуется в JPEG только для выгрузки.</p>{!photos.length?<p>Добавьте фотографии в разделе «Фото» этой карточки.</p>:<div className="avito-photos">{[...photos].sort((a,b)=>(v.photoIds.includes(a.id)?v.photoIds.indexOf(a.id):1000)-(v.photoIds.includes(b.id)?v.photoIds.indexOf(b.id):1000)).map(f=>{const index=v.photoIds.indexOf(f.id);return <article key={f.id} className={index>=0?'selected':''}><label><img src={'/api/cars/'+car.id+'/files/'+f.id} alt={f.name} loading="lazy"/><span><input type="checkbox" checked={index>=0} onChange={e=>change('photoIds',e.target.checked?[...v.photoIds,f.id]:v.photoIds.filter(x=>x!==f.id))}/>{index===0?'Обложка':index>0?'Фото '+(index+1):'Выбрать'}</span></label>{index>=0&&<div className="avito-photo-actions"><button type="button" title="Раньше" disabled={index===0} onClick={()=>move(f.id,-1)}><ArrowUp size={16}/></button><button type="button" title="Позже" disabled={index===v.photoIds.length-1} onClick={()=>move(f.id,1)}><ArrowDown size={16}/></button>{index>0&&<button type="button" onClick={()=>change('photoIds',[f.id,...v.photoIds.filter(x=>x!==f.id)])}>Обложка</button>}</div>}</article>;})}</div>}</section>
   <div className="avito-savebar"><span>{dirty?'Есть несохранённые изменения':car.avito?'Черновик сохранён':'Черновик ещё не сохранён'}</span><button className="btn primary" type="submit"><Save size={17}/> Сохранить черновик</button></div>
  </fieldset></form>
  {proposal&&<AdDraftDialog channel="Авито" title={proposal.title} description={proposal.description} advantages={proposal.advantages} disabled={disabled} onClose={()=>setProposal(null)} onApply={()=>{setV(x=>({...x,title:proposal.title,fields:{...x.fields,Description:proposal.description}}));setProposal(null);setBundle(null);setApplied(true);}}/>}
  {market&&<section className="panel avito-market"><div className="panel-title"><h3>Сравнение предложений</h3><span>{new Date(market.checkedAt).toLocaleString('ru-RU')}</span></div><div className="avito-metrics"><div><span>Ваша цена</span><strong>{money(market.currentPrice)}</strong></div><div><span>Средняя по выборке · {market.offers.length} авто</span><strong>{money(market.average)}</strong></div><div><span>Медиана выборки</span><strong>{money(market.median)}</strong></div></div><p>{market.recommendation}</p><div className="avito-offers">{market.offers.map(o=><a href={o.url} target="_blank" rel="noreferrer" key={o.url}><span>{o.title}<small>{o.year} · {o.mileage==null?'Пробег не указан':o.mileage+' км'}</small></span><b>{money(o.priceRub)} ↗</b></a>)}</div><p className="avito-note">{market.comment}</p></section>}
  <section className="panel avito-export" ref={checkRef}><div className="panel-title"><div><h3>Подготовить Авито</h3><p>Excel по исходному шаблону + ZIP с выбранными фото.</p></div>{check.ready?<CheckCircle2 size={24}/>:<AlertCircle size={24}/>}</div><div className="avito-actions"><button className="btn" onClick={()=>setCheckVisible(true)}>Проверить поля</button><button className="btn primary" disabled={disabled||dirty||!car.avito?.selected} onClick={()=>prepare(false)}><Download size={17}/> Этот автомобиль</button><button className="btn" disabled={disabled||dirty||!selectedCars.length} onClick={()=>prepare(true)}>Все выбранные · {selectedCars.length}</button></div>{dirty&&<p className="avito-note">Перед подготовкой выгрузки сохраните черновик.</p>}{checkVisible&&<div className="avito-checks">{check.errors.length?<><b>Нужно дополнить</b><ul>{check.errors.map((e,i)=><li key={e.field+i}><button type="button" onClick={()=>{const el=document.getElementById('avito-'+e.field);const details=el?.closest('details');if(details)details.open=true;el?.focus();el?.scrollIntoView({block:'center',behavior:'smooth'});}}>{e.label}: {e.message}</button></li>)}</ul></>:<p>Основные поля заполнены. Проверьте готовый файл в Авито перед загрузкой.</p>}{check.warnings.map(x=><p className="avito-note" key={x}>{x}</p>)}</div>}
   <p className="avito-warning">Загрузка неполного файла в Авито может снять объявления, отсутствующие в нём. Для действующего аккаунта сверяйте полный список объявлений и используйте общую выгрузку.</p><p className="avito-note">Паспорта, договоры, расходы и данные покупателя/продавца не экспортируются. Загрузка в кабинет Авито выполняется вручную. Посты Telegram готовятся в отдельной вкладке. Instagram пока не подключён.</p>
   {bundle&&<div className="avito-downloads"><b>Подготовлено автомобилей: {bundle.count}</b><a className="btn primary" href={bundle.xlsx} download="VECTOR_Avito.xlsx">Скачать Excel</a><a className="btn" href={bundle.photos} download="VECTOR_Avito_photos.zip">Скачать фото ZIP</a><a href="https://www.avito.ru/autoload/settings" target="_blank" rel="noreferrer">Открыть кабинет автозагрузки ↗</a><small>Скачайте оба файла. При загрузке Excel приложите архив фотографий.</small></div>}
  </section>
  {busy&&<div className="avito-progress" role="status"><Loader2 className="spin" size={18}/>{busy}</div>}{error&&<div className="error" role="alert">{error}</div>}
 </div>;
}
