import{zipSync,strToU8}from'fflate';

const esc=s=>String(s??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
const forms=(n,a,b,c)=>{n=Math.abs(n)%100;const n1=n%10;return n>10&&n<20?c:n1===1?a:n1>=2&&n1<=4?b:c};
const ONES=[['','один','два','три','четыре','пять','шесть','семь','восемь','девять'],['','одна','две','три','четыре','пять','шесть','семь','восемь','девять']];
const TEENS=['десять','одиннадцать','двенадцать','тринадцать','четырнадцать','пятнадцать','шестнадцать','семнадцать','восемнадцать','девятнадцать'];
const TENS=['','','двадцать','тридцать','сорок','пятьдесят','шестьдесят','семьдесят','восемьдесят','девяносто'];
const HUNDREDS=['','сто','двести','триста','четыреста','пятьсот','шестьсот','семьсот','восемьсот','девятьсот'];
const GROUPS=[['','','',0],['тысяча','тысячи','тысяч',1],['миллион','миллиона','миллионов',0],['миллиард','миллиарда','миллиардов',0]];
export function numberWords(value){let n=Math.trunc(Math.abs(Number(value)));if(!n)return'ноль';const out=[];for(let g=0;n&&g<GROUPS.length;g++,n=Math.floor(n/1000)){const x=n%1000;if(!x)continue;const words=[];words.push(HUNDREDS[Math.floor(x/100)]);const rest=x%100;if(rest>=10&&rest<20)words.push(TEENS[rest-10]);else{words.push(TENS[Math.floor(rest/10)]);words.push(ONES[GROUPS[g][3]][rest%10])}if(g)words.push(forms(x,...GROUPS[g].slice(0,3)));out.unshift(words.filter(Boolean).join(' '))}return out.join(' ')}
export function amountWords(value,currency){const cents=Math.round(Number(value)*100);const whole=Math.floor(cents/100),fraction=cents%100;if(currency==='USD')return`${numberWords(whole)} ${forms(whole,'доллар США','доллара США','долларов США')} ${String(fraction).padStart(2,'0')} ${forms(fraction,'цент','цента','центов')}`;return`${numberWords(whole)} ${forms(whole,'рубль','рубля','рублей')} ${String(fraction).padStart(2,'0')} ${forms(fraction,'копейка','копейки','копеек')}`}
const dateRu=d=>{const[year,month,day]=d.split('-');return`${day}.${month}.${year}`};
const longDate=d=>{const[year,month,day]=d.split('-');const months=['января','февраля','марта','апреля','мая','июня','июля','августа','сентября','октября','ноября','декабря'];return`«${day}» ${months[Number(month)-1]} ${year} г.`};
const money=n=>new Intl.NumberFormat('ru-RU',{minimumFractionDigits:2,maximumFractionDigits:2}).format(n);
function partyText(p,role){const passport=[p.passportSeries,p.passportNumber].filter(Boolean).join(' ');const parts=[p.fullName];if(p.birthDate)parts.push(`${dateRu(p.birthDate)} г.р.`);if(passport)parts.push(`паспорт: ${passport}`);if(p.passportIssuedBy)parts.push(`выдан: ${p.passportIssuedBy}`);if(p.passportIssueDate)parts.push(`${dateRu(p.passportIssueDate)} г.`);if(p.passportCode)parts.push(`код подразделения ${p.passportCode}`);if(p.address)parts.push(`адрес регистрации: ${p.address}`);parts.push(`далее — «${role==='seller'?'Продавец':'Покупатель'}»`);return parts.join(', ')}
const run=(text,bold=false,size=21)=>`<w:r><w:rPr><w:rFonts w:ascii="Times New Roman" w:hAnsi="Times New Roman" w:eastAsia="Times New Roman"/><w:sz w:val="${size}"/><w:szCs w:val="${size}"/>${bold?'<w:b/>':''}</w:rPr><w:t xml:space="preserve">${esc(text)}</w:t></w:r>`;
const para=(text,{align='both',bold=false,after=45,before=0,indent=0,first=567,size=21,keep=false}={})=>`<w:p><w:pPr><w:jc w:val="${align}"/><w:spacing w:before="${before}" w:after="${after}" w:line="230" w:lineRule="auto"/>${indent||first?`<w:ind w:left="${indent}" w:firstLine="${first}"/>`:''}${keep?'<w:keepNext/>':''}</w:pPr>${run(text,bold,size)}</w:p>`;
const cell=(text,{align='left',bold=false,width=4650}={})=>`<w:tc><w:tcPr><w:tcW w:w="${width}" w:type="dxa"/><w:tcMar><w:top w:w="0" w:type="dxa"/><w:left w:w="0" w:type="dxa"/><w:bottom w:w="0" w:type="dxa"/><w:right w:w="0" w:type="dxa"/></w:tcMar></w:tcPr>${para(text,{align,bold,after:0,first:0,size:21})}</w:tc>`;
const table=rows=>`<w:tbl><w:tblPr><w:tblW w:w="9300" w:type="dxa"/><w:tblBorders><w:top w:val="nil"/><w:left w:val="nil"/><w:bottom w:val="nil"/><w:right w:val="nil"/><w:insideH w:val="nil"/><w:insideV w:val="nil"/></w:tblBorders></w:tblPr>${rows.map(r=>`<w:tr>${r}</w:tr>`).join('')}</w:tbl>`;

export function generateContractDocx({car,seller,buyer,contractNo,contractDate,priceUsd,priceRub,invoiceNo,invoiceDate}){
 const sellerLine=partyText(seller,'seller'),buyerLine=partyText(buyer,'buyer');
 const doc=`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body>
 ${para(`Договор купли – продажи автомобиля № ${contractNo}`,{align:'center',bold:true,after:100,first:0,size:26,keep:true})}
 ${table([[cell('г. Бишкек'),cell(longDate(contractDate),{align:'right'})].join('')])}
 ${para(`${sellerLine}, с одной стороны, и ${buyerLine}, с другой стороны, а вместе именуемые «Стороны», заключили настоящий договор о нижеследующем:`,{before:90})}
 ${para('1. Продавец обязуется передать в собственность Покупателя, а Покупатель обязуется принять и оплатить следующее транспортное средство:',{keep:true})}
 ${para(`Марка, модель – ${car.brand} ${car.model}`,{indent:567,first:0,after:15})}
 ${para(`Года выпуска ТС – ${car.year}`,{indent:567,first:0,after:15})}
 ${para(`Идентификационный номер (VIN) – ${car.vin}`,{indent:567,first:0,after:45})}
 ${para(`Стоимость передаваемого транспортного средства составляет ${money(priceUsd)} (${amountWords(priceUsd,'USD')}) и эквивалентна ${money(priceRub)} (${amountWords(priceRub,'RUB')}). Инвойс № ${invoiceNo} от ${dateRu(invoiceDate)} г.`,{})}
 ${para('Продавец продает ТС свободным от любых имущественных прав и претензий третьих лиц. При заключении настоящего договора Транспортное средство никому не продано, не заложено, в споре и под арестом не состоит.')}
 ${para('2. Стороны определили, что оплата указанного в настоящем договоре транспортного средства Покупателем будет произведена безналичным путем. Передача Продавцом транспортного средства осуществлена без оформления акта приёма-передачи. Переход права собственности ТС от Продавца к Покупателю осуществлён сразу после его оплаты Покупателем и передачи транспортного средства Продавцом.')}
 ${para('3. Настоящий Договор составлен в трёх экземплярах, имеющих одинаковую юридическую силу.')}
 ${para('Подписи сторон:',{bold:true,before:70,after:70,first:0,keep:true})}
 ${table([[cell('Продавец: ____________________', {width:4650}),cell('Покупатель: ____________________',{width:4650})].join(''),[cell(seller.fullName,{width:4650,bold:true}),cell(buyer.fullName,{width:4650,bold:true})].join('')])}
 <w:sectPr><w:pgSz w:w="11906" w:h="16838"/><w:pgMar w:top="850" w:right="850" w:bottom="850" w:left="850" w:header="425" w:footer="425" w:gutter="0"/></w:sectPr></w:body></w:document>`;
 const files={
  '[Content_Types].xml':strToU8('<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/><Override PartName="/word/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.styles+xml"/><Override PartName="/docProps/core.xml" ContentType="application/vnd.openxmlformats-package.core-properties+xml"/><Override PartName="/docProps/app.xml" ContentType="application/vnd.openxmlformats-officedocument.extended-properties+xml"/></Types>'),
  '_rels/.rels':strToU8('<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/package/2006/relationships/metadata/core-properties" Target="docProps/core.xml"/><Relationship Id="rId3" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/extended-properties" Target="docProps/app.xml"/></Relationships>'),
  'word/document.xml':strToU8(doc),'word/_rels/document.xml.rels':strToU8('<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"/>'),
  'word/styles.xml':strToU8('<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:styles xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:docDefaults><w:rPrDefault><w:rPr><w:rFonts w:ascii="Times New Roman" w:hAnsi="Times New Roman" w:eastAsia="Times New Roman"/><w:sz w:val="21"/><w:szCs w:val="21"/></w:rPr></w:rPrDefault></w:docDefaults><w:style w:type="paragraph" w:default="1" w:styleId="Normal"><w:name w:val="Normal"/><w:qFormat/></w:style></w:styles>'),
  'docProps/core.xml':strToU8('<?xml version="1.0" encoding="UTF-8" standalone="yes"?><cp:coreProperties xmlns:cp="http://schemas.openxmlformats.org/package/2006/metadata/core-properties" xmlns:dc="http://purl.org/dc/elements/1.1/"><dc:title>Договор купли-продажи автомобиля</dc:title><dc:creator>VECTOR CRM</dc:creator></cp:coreProperties>'),
  'docProps/app.xml':strToU8('<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Properties xmlns="http://schemas.openxmlformats.org/officeDocument/2006/extended-properties"><Application>VECTOR CRM</Application></Properties>')
 };
 return zipSync(files,{level:6});
}
