export const BASIS_FIELDS=[['krw','Стоимость авто до Бишкека, ₩'],['krwPerUsd','Курс: ₩ за $1'],['tpoUsd','ТПО — растаможка в Бишкеке, $'],['usdRub','Курс: ₽ за $1'],['logisticsUsd','Логистика Бишкек—Воронеж, $'],['documentsRub','Документы, ₽'],['recyclingRub','Утилизационный сбор, ₽']];
export const PURCHASE_CURRENCIES=['USD','KRW','CNY','EUR','RUB'];
export const currencySymbol=c=>({USD:'$',KRW:'₩',CNY:'¥',EUR:'€',RUB:'₽'}[c]||c);
export const defaultCurrency=country=>country==='Корея'?'KRW':country==='Китай'?'CNY':'USD';
export const rateField=c=>({KRW:'krwPerUsd',CNY:'cnyPerUsd',EUR:'eurPerUsd'}[c]);
export function purchaseInfo(c){const b=c.costBasis||{},modern=Object.hasOwn(b,'purchaseAmount')||b.krw==null;return {key:modern?'purchaseAmount':'krw',amount:modern?b.purchaseAmount:b.krw,currency:modern?b.purchaseCurrency||defaultCurrency(c.country):'KRW'};}
export function expenseFields(c){const p=purchaseInfo(c);return [[p.key,'Стоимость автомобиля',currencySymbol(p.currency)],...EXPENSE_FIELDS.slice(1).filter(([k])=>k!=='tpoUsd'||c.customsCountry!=='Россия'||Number(c.costBasis?.tpoUsd)>0).map(x=>x[0]==='logisticsUsd'?['logisticsUsd','Логистика','$']:x)];}
export const EXPENSE_FIELDS=[['krw','Автомобиль до Бишкека','₩'],['tpoUsd','ТПО · растаможка','$'],['logisticsUsd','Бишкек → Воронеж','$'],['documentsRub','Документы','₽'],['recyclingRub','Утилизационный сбор','₽'],['logisticsRub','Ранее внесённая доставка','₽']];
const fail=label=>{throw Object.assign(new Error('Проверьте поле «'+label+'»'),{status:400})};
const number=(value,label,rate=false)=>{if(value===undefined||value===null||value==='')return null;const n=Number(value);if(!Number.isFinite(n)||n<0||n>1e12||(rate&&n===0))fail(label);return n};
export function basisInput(b={}){const out={};for(const [k,label] of [...BASIS_FIELDS,['logisticsRub','Ранее сохранённая логистика, ₽']])out[k]=number(b[k],label,['usdRub','krwPerUsd'].includes(k));
 if(Object.hasOwn(b,'purchaseAmount')){out.purchaseAmount=number(b.purchaseAmount,'Стоимость автомобиля');if(!PURCHASE_CURRENCIES.includes(b.purchaseCurrency))fail('Валюта автомобиля');out.purchaseCurrency=b.purchaseCurrency;out.krw=null;}for(const k of ['cnyPerUsd','eurPerUsd'])if(b[k]!==undefined)out[k]=number(b[k],'Курс '+k,true);
 if(b.expenses!==undefined){if(!b.expenses||typeof b.expenses!=='object'||Array.isArray(b.expenses))fail('Настройки расходов');out.expenses={};for(const [k,label,currency] of [...EXPENSE_FIELDS,['purchaseAmount','Стоимость автомобиля',currencySymbol(b.purchaseCurrency)]]){const m=b.expenses[k];if(m===undefined)continue;if(!m||typeof m!=='object'||Array.isArray(m)||m.paid!==undefined&&typeof m.paid!=='boolean')fail(label);out.expenses[k]={paid:m.paid===true,...(currency!=='₽'?{usdRub:number(m.usdRub,'Курс доллара · '+label,true)}:{}),...(['₩','¥','€'].includes(currency)?{perUsd:number(m.perUsd,'Курс валюты · '+label,true)}:{}),...(currency==='₩'?{krwPerUsd:number(m.krwPerUsd,'Курс воны · '+label,true)}:{})};}}return out;}
const round=n=>Math.round((n+Number.EPSILON)*100)/100;
export function expensePaid(c,key){return c.costBasis?.expenses?.[key]?.paid??(key==='recyclingRub'&&c.utilizationStatus==='Оплачен');}
export function basisExpense(c,key,currency){const b=c.costBasis||{},m=b.expenses?.[key]||{},amount=Number(b[key])||0,usdRub=m.usdRub??(key!=='purchaseAmount'?b.expenses?.purchaseAmount?.usdRub:undefined)??b.usdRub,code=key==='purchaseAmount'?b.purchaseCurrency:key==='krw'?'KRW':currency==='$'?'USD':'RUB',perUsd=m.perUsd??(code==='KRW'?m.krwPerUsd:undefined)??b[rateField(code)];const usd=currency==='₽'?null:currency==='$'?amount:perUsd?amount/perUsd:null;const rub=currency==='₽'?amount:amount===0?0:usd!==null&&usdRub?usd*usdRub:null;return{amount,usd,rub,usdRub,krwPerUsd:perUsd,perUsd,paid:expensePaid(c,key)};}
export function expenseRate(c,x){return x.currency==='RUB'?1:x.rate!==null&&x.rate!==undefined&&x.rate!==''?Number(x.rate):x.currency==='USD'?Number(c.costBasis?.usdRub)||null:null;}
export function costSummary(c){const b=c.costBasis||{},rate=Number(b.usdRub)||0;let rubTotal=0,paidRub=0,unpaidRub=0,missing=false,paidMissing=false,unpaidMissing=false,dollarPart=0,rubExpenses=0,missingWon=false;
 const add=(rub,paid)=>{if(rub===null){missing=true;if(paid)paidMissing=true;else unpaidMissing=true;}else{rubTotal+=rub;if(paid)paidRub+=rub;else unpaidRub+=rub;}};
 for(const [key,,currency] of expenseFields(c)){const x=basisExpense(c,key,currency);add(x.rub,x.paid);if(currency==='₽')rubExpenses+=x.amount;else dollarPart+=x.usd||0;if(!['₽','$'].includes(currency)&&x.amount&&!x.perUsd)missingWon=true;}
 for(const x of c.costs||[]){const r=expenseRate(c,x),rub=r?round(x.amount*r):null;add(rub,x.paid===true);if(rub!==null)rubExpenses+=rub;}
 return{usd:round(dollarPart+(rate?rubExpenses/rate:0)),rub:missing?null:round(rubTotal),usdPartial:missingWon||(!rate&&rubExpenses>0)||missing,paidRub:paidMissing?null:round(paidRub),unpaidRub:unpaidMissing?null:round(unpaidRub),rubExpenses:round(rubExpenses),missingWon,rate};}
