import {photoProxy} from './encar-photos.js';
import {downloadProposal} from './encar-proposal.js';
import {POWER_SEED,powerIdentity,powerMatches,resolvePower,applyPower,cleanPower} from './encar-power.js';
import {parsePowerTable,powerTemplate} from './encar-power-import.js';
import React,{useState,useEffect} from 'react';
import {ExternalLink,Download,Save,Plus,RefreshCw} from 'lucide-react';
import {ENCAR_FIELDS,LEGACY_FIELDS,emptyQuote,quoteResult,readEncarImport,newFormulaCopy} from './encar.js';
import {UTIL_SOURCE} from './encar-util.js';
import table from './encar-table.json' with {type:'json'};
import './encar.css';
const fmt=n=>n==null?'—':new Intl.NumberFormat('ru-RU',{maximumFractionDigits:2}).format(n);
export default function Encar({api,readOnly}){
 const[q,set]=useState(()=>readEncarImport(location.hash)||emptyQuote()),[quotes,sq]=useState([]),[query,squery]=useState(''),[error,se]=useState(''),[notice,sn]=useState(''),[busy,sb]=useState(false),[rateBusy,srb]=useState(false),[link,sl]=useState(''),[importBusy,sib]=useState(false);
 const [localPhotos,setLocalPhotos]=useState([]);
 const [powerRows,setPowerRows]=useState(POWER_SEED),[powerBusy,setPowerBusy]=useState(false),[pdfBusy,setPdfBusy]=useState(false),[pendingRows,setPendingRows]=useState([]);
 const modern=Number(q.formulaVersion)===2;const result=quoteResult(q);const change=(k,v)=>set(p=>{const next={...p,[k]:v};if(p.powerCatalogKey&&['brand','model','trim','year','engine','market'].includes(k)){next.powerHp='';next.powerSource='';next.powerCatalogKey='';next.powerReference='';next.powertrain='ice';}if(k==='powerHp')next.powerCatalogKey='';return next;});
 useEffect(()=>{api('/encar/power').then(r=>setPowerRows(r.rows)).catch(e=>se(e.message))},[]);
 useEffect(()=>{set(p=>resolvePower(p,powerRows))},[powerRows,q.brand,q.model,q.trim,q.year,q.engine,q.market]);
 async function list(){try{sq((await api('/encar/quotes')).quotes)}catch(e){se(e.message)}}
 useEffect(()=>{list();const take=()=>{const imported=readEncarImport(location.hash);if(imported){set(imported);sn('Данные из Encar получены. Проверьте их и выберите строку таблицы ТПО.');history.replaceState(null,'','#encar');}};take();window.addEventListener('hashchange',take);return()=>window.removeEventListener('hashchange',take)},[]);
 async function rates(){srb(true);se('');try{const r=await api('/encar/rates');set(p=>({...p,...r}));sn('Курсы обновлены. При необходимости укажите свой курс покупки валюты.')}catch(e){se(e.message)}finally{srb(false)}}
 async function importLink(){sib(true);se('');sn('');try{
  const imported=await api('/encar/import',{method:'POST',body:{url:link}});
  let rateData={},rateWarning='';try{rateData=await api('/encar/rates')}catch(e){rateWarning=e.message}
  setLocalPhotos([]);set({...emptyQuote(),...imported.quote,...rateData});squery('');
  sn(['Объявление загружено. Проверьте расходы и параметры утильсбора.',...imported.warnings,rateWarning].filter(Boolean).join(' '));
 }catch(e){se(e.message)}finally{sib(false)}}
 async function save(){sb(true);se('');sn('');try{const saved=await api('/encar/quotes',{method:'POST',body:q});set(saved);await list();sn('Расчёт сохранён в облаке')}catch(e){se(e.message)}finally{sb(false)}}
 async function rememberPower(){setPowerBusy(true);se('');try{const previous=powerMatches(q,powerRows)[0];const row=await api('/encar/power',{method:'POST',body:{...q,source:q.powerSource||'Подтверждено пользователем',sourceUrl:q.powerReference||'',expectedUpdatedAt:previous?.updatedAt}});const rows=[row,...powerRows.filter(r=>powerIdentity(r)!==powerIdentity(row))];setPowerRows(rows);set(p=>applyPower(p,row));sn('Мощность сохранена для этой модификации.')}catch(e){se(e.message)}finally{setPowerBusy(false)}}
 async function importPowers(e){const file=e.target.files?.[0];e.target.value='';if(!file)return;try{if(file.size>3000000)throw new Error('Таблица должна быть меньше 3 МБ');const parsed=parsePowerTable(new Uint8Array(await file.arrayBuffer()),file.name);const validated=parsed.map(r=>{try{return cleanPower(r)}catch(e){throw new Error('Строка '+r.line+': '+e.message)}});const keys=new Set(powerRows.map(powerIdentity));const added=validated.filter(r=>{const k=powerIdentity(r);if(keys.has(k))return false;keys.add(k);return true;});setPendingRows(added);sn('Прочитано '+validated.length+'. Новых модификаций: '+added.length+'. Совпадения пропущены. Проверьте таблицу ниже и нажмите «Добавить в справочник».');se('')}catch(e){se(e.message)}}
 async function savePowers(){setPowerBusy(true);se('');const saved=[];try{for(const row of pendingRows)saved.push(await api('/encar/power',{method:'POST',body:row}));sn('В справочник добавлено: '+saved.length)}catch(e){se('Добавлено '+saved.length+'. '+e.message)}finally{setPowerRows(p=>[...saved,...p]);setPendingRows(p=>p.slice(saved.length));setPowerBusy(false)}}
 async function addProposalPhotos(e){const files=[...e.target.files];e.target.value='';const room=9-(q.photoUrls?.length||0)-localPhotos.length;if(files.length>room){se('В PDF можно добавить до 9 фотографий. Удалите лишние или выберите меньше файлов.');return;}if(files.some(f=>!['image/jpeg','image/png','image/webp'].includes(f.type)||f.size>15000000)){se('Выберите JPG, PNG или WEBP до 15 МБ каждый.');return;}setLocalPhotos(p=>[...p,...files.map(blob=>({blob,id:crypto.randomUUID()}))]);se('');}
 async function offer(){setPdfBusy(true);se('');try{await downloadProposal(q,localPhotos);sn('Коммерческое предложение сохранено в PDF.')}catch(e){se(e.message)}finally{setPdfBusy(false)}}
 function template(){const url=URL.createObjectURL(new Blob([powerTemplate()],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='VECTOR-power-template.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),10000)}
 const select=(k,label,options)=><label className="field"><span>{label}</span><select value={q[k]??''} onChange={e=>change(k,e.target.value)}>{options.map(([v,t])=><option key={v} value={v}>{t}</option>)}</select></label>;
 const line=(label,value,currency='₽')=><div className="encar-line"><span>{label}</span><b>{fmt(value)} {currency}</b></div>;
 const choices=table.filter(r=>[r.brand,r.model,r.engine,r.year].join(' ').toLowerCase().includes(query.trim().toLowerCase()));
 const field=(k,label,type='text')=><label className="field" key={k}><span>{label}</span><input type={type} min={type==='number'?0:undefined} step={type==='number'?'any':undefined} value={q[k]??''} onChange={e=>{change(k,e.target.value);if(['eurUsd','usdRub','krwPerUsd'].includes(k))change('rateSource','Вручную');if(k==='powerHp')change('powerSource','Вручную');if(['year','utilYear'].includes(k))change('utilAge','')}}/></label>;
 return <div className="encar-workspace"><div className="page-heading"><div><div className="eyebrow">VECTOR / ENCAR</div><h1>Расчёт Encar</h1><p>Стоимость автомобиля до Воронежа</p></div><div className="heading-actions"><a className="btn" href="https://www.encar.com/" target="_blank" rel="noreferrer"><ExternalLink size={17}/>Открыть Encar</a><button className="btn" onClick={()=>{setLocalPhotos([]);set(emptyQuote());se('');sn('');squery('')}}><Plus size={17}/>Новый расчёт</button></div></div>
 <form className="panel encar-link" onSubmit={e=>{e.preventDefault();importLink()}}><label className="field"><span>Ссылка на автомобиль Encar</span><input type="url" required value={link} onChange={e=>sl(e.target.value)} placeholder="https://fem.encar.com/cars/detail/…" disabled={importBusy}/></label><button className="btn primary" disabled={importBusy||readOnly}>{importBusy?'Загружаю объявление…':'Рассчитать по ссылке'}</button></form>
 <details className="panel encar-help"><summary>Как передать объявление без копирования ссылки</summary><p>На компьютере установите Tampermonkey, затем наш скрипт. Отключите старые отдельные модули калькулятора. Откройте объявление Encar и нажмите «Передать в VECTOR». CRM откроет заполненный черновик — останется проверить ТПО и сохранить.</p><a className="btn" href="/encar/vector-encar.user.js" download><Download size={17}/>Скачать скрипт Encar</a><p>Вход в CRM остаётся через вашу учётную запись. Автомобиль и его себестоимость не меняются при передаче расчёта.</p></details>
 {error&&<div className="encar-error" role="alert">{error}</div>}{notice&&<div className="encar-notice" role="status">{notice}</div>}
 {!modern&&<div className="encar-notice">Этот расчёт сохранён по прежней формуле. <button className="btn" onClick={()=>{set(newFormulaCopy(q));sn('Создан новый черновик по формуле со скидкой и надбавкой. Прежний расчёт сохранён.')}}>Создать расчёт по новой формуле</button></div>}
 <div className="encar-layout"><section className="panel"><div className="panel-title"><h2>Автомобиль и расходы</h2></div><div className="form-grid">{field('brand','Марка')}{field('model','Модель')}{field('trim','Модификация')}{field('year','Год выпуска')}{field('engine','Объём двигателя, см³')}{modern&&field('powerHp','Мощность, л.с. (метрические)','number')}{field('vin','VIN')}{field('mileage','Пробег, км')}{field('url','Объявление Encar')}{modern&&field('market','Рынок / страна спецификации')}</div>{modern&&<div className="encar-table-picker"><h3>Справочник мощности</h3><p>{q.powerHp?fmt(Number(q.powerHp))+' л.с. · '+(q.powerSource||'Введено вручную'):'Точного совпадения пока нет. Укажите мощность и запомните модификацию.'}</p>{q.powerReference?.startsWith('https://')&&<a href={q.powerReference} target="_blank" rel="noreferrer">Источник характеристик ↗</a>}
 {select('powerKind','Какую мощность сохраняем',[['system','Общая мощность установки'],['engine','Мощность ДВС']])}{field('powerReference','Ссылка на источник (необязательно)')}
 {!readOnly&&<button className="btn" disabled={powerBusy} onClick={rememberPower}>Запомнить для этой модификации</button>}
 <details><summary>Загрузка справочника · {powerRows.length} записей</summary><p className="fine-print">Совпадение по марке, модели, модификации, году, объёму и рынку. Правка мощности в расчёте не меняет справочник без кнопки «Запомнить».</p><button className="btn" onClick={template}>Скачать шаблон для Excel</button>{!readOnly&&<label className="btn">Загрузить Excel / CSV<input type="file" hidden accept=".xlsx,.csv" disabled={powerBusy} onChange={importPowers}/></label>}{pendingRows.length>0&&<><div className="table-wrap"><table><thead><tr><th>Автомобиль</th><th>Год</th><th>Мощность</th></tr></thead><tbody>{pendingRows.map((r,i)=><tr key={i}><td>{r.brand} {r.model} {r.trim}</td><td>{r.year}</td><td>{r.powerHp} л.с.</td></tr>)}</tbody></table></div><button className="btn primary" disabled={powerBusy||readOnly} onClick={savePowers}>{powerBusy?'Сохраняю…':'Добавить в справочник'}</button><button className="btn" disabled={powerBusy} onClick={()=>setPendingRows([])}>Отмена</button></>}</details></div>}
 <div className="encar-table-picker"><h3>Таблица ТПО · с 1 февраля 2026</h3><label className="field"><span>Найти марку, модель, объём или год</span><input value={query} onChange={e=>squery(e.target.value)} placeholder="Например: BMW 740"/></label><label className="field"><span>Строка таблицы · {table.length} вариантов</span><select value={q.tableId||''} onChange={e=>{const r=table.find(x=>x.id===e.target.value);set(p=>({...p,tableId:r?.id||'',eur:r?.eur??'',brand:p.brand||r?.brand||'',model:p.model||r?.model||'',year:p.year||r?.year||'',engine:p.engine||r?.engine||''}))}}><option value="">Выберите стоимость в евро</option>{(q.tableId&&!choices.some(r=>r.id===q.tableId)?[table.find(r=>r.id===q.tableId),...choices]:choices).filter(Boolean).map(r=><option key={r.id} value={r.id}>{r.brand} {r.model} · {r.engine||'объём не указан'} · {r.year} · {fmt(r.eur)} €</option>)}</select></label><div className="encar-line"><span>Исходная стоимость в евро</span><b>{fmt(q.eur===''?null:Number(q.eur))} €</b></div>{field('eurUsd','Курс ТПО: долларов за 1 евро','number')}<div className="encar-tpo-total"><span>ТПО {q.manualTpo!==''&&q.manualTpo!=null?'· вручную':'· по формуле'}</span><strong>{fmt(result.tpo)} $</strong></div>{result.tpo===null&&<p className="encar-missing">{Number(q.eur)>0?'Стоимость по таблице найдена. Введите курс долларов за 1 евро или нажмите «Обновить курсы».':'Выберите строку таблицы или укажите ТПО вручную.'}</p>}<details><summary>Указать ТПО вручную</summary>{field('manualTpo','Ручной ТПО, $ — пустое поле включает расчёт по формуле','number')}</details><small>ТПО = стоимость в евро × 48% × USD за 1 EUR. Для поиска объём округляется вверх до 100 см³: 2 998 → 3 000. Фактический объём сохраняется. Для диапазонов объёма и объединённых моделей выберите подходящую строку вручную.</small></div>
 <div className="panel-title"><h3>Курсы и расходы</h3><button className="btn" disabled={rateBusy} onClick={rates}><RefreshCw size={16}/>{rateBusy?'Загрузка…':'Обновить курсы'}</button></div><p className="fine-print">{q.rateSource||'Курсы пока не указаны'}{q.rateDate?' · '+q.rateDate:''}</p><div className="form-grid">{(modern?ENCAR_FIELDS:LEGACY_FIELDS.filter(([k])=>k!=='eurUsd')).map(([k,l])=>field(k,l,'number'))}</div>
 {modern&&<><p className="fine-print">Скидка вычитается из цены авто. Расходы до Бишкека добавляются в вонах. Надбавка применяется к долларовой части после перевода в рубли, до документов и утильсбора.</p>
 <div className="encar-table-picker"><h3>Утилизационный сбор</h3><p className="fine-print">Легковой автомобиль M1 · стандартные ставки 2026. Фактический объём {q.engine||'—'} см³. {q.powerSource||'Мощность можно указать выше вручную.'}</p><div className="form-grid">
 <div className="field"><span>Режим расчёта</span><strong>Бензин / дизель (ДВС)</strong><small>Для всех автомобилей используется таблица ДВС. Тип из Encar не меняет режим расчёта.</small></div>
 {select('utilAge','Возраст на дату уплаты',[['','Выберите возраст'],['new','Не более 3 лет'],['old','Более 3 лет']])}
 {select('utilRegime','Условия расчёта',[['standard','Обычный ввоз / для перепродажи'],['personal','Личный ввоз / особые условия — вручную']])}
 {field('utilYear','Год уплаты утильсбора','number')}{field('eaeuRub','Доплата ЕАЭС по расчёту брокера, ₽','number')}
 </div>{line('По стандартной таблице',result.util?.baseRub)}{result.util?.coefficient&&<small>20 000 ₽ × {fmt(result.util.coefficient)} · мощность {fmt(result.util.kw)} кВт</small>}
 {field('utilRub','Утильсбор вручную, ₽ — заменяет всю сумму, включая доплату','number')}
 <div className="encar-tpo-total"><span>Утильсбор в итоговом расчёте{result.util?.manual?' · вручную':''}</span><strong>{fmt(result.util?.rub)} ₽</strong></div>
 {result.util?.reason&&<p className="encar-missing">{result.util.reason}.</p>}
 <small>При ввозе через ЕАЭС к табличному сбору могут добавляться разницы пошлины, НДС и акциза. Нулевая доплата задана предварительно — уточните её у брокера. Мощность можно исправить вручную. Для личного ввоза используйте подтверждённую ручную сумму.</small><a href={UTIL_SOURCE} target="_blank" rel="noreferrer">Постановление №1291 · ставки проверены 11.09.2026</a>
 </div></>}

 </section><aside><section className="panel encar-result"><span className="eyebrow">ПРЕДВАРИТЕЛЬНАЯ СТОИМОСТЬ</span><strong>{fmt(result.rub)} ₽</strong><p>{fmt(result.usd)} $</p>{modern?<>
 {line('Авто после скидки',result.discountedKrw,'₩')}{line('С расходами до Бишкека',result.landedKrw,'₩')}{line('До Бишкека в долларах',result.priceUsd,'$')}{line('Брокер',Number(q.bishkekUsd)||0,'$')}{line('ТПО',result.tpo,'$')}{line('До Воронежа',Number(q.deliveryUsd)||0,'$')}{line('Итого долларовая часть',result.subtotalUsd,'$')}{line('После перевода в рубли',result.convertedRub)}{line('Надбавка '+(q.markupPct??'—')+'%',result.markupRub)}{line('Документы',Number(q.documentsRub)||0)}{line('Утильсбор',result.util?.rub)}{result.rub===null&&line('Без утильсбора',result.beforeUtilRub)}
 </>:<>{line('Автомобиль',result.priceUsd,'$')}{line('ТПО',result.tpo,'$')}</>}{result.missing.length>0&&<p className="encar-missing">Для полного итога заполните: {result.missing.join(', ')}.</p>}<button className="btn primary" disabled={readOnly||busy||importBusy} onClick={save}><Save size={17}/>{busy?'Сохранение…':'Сохранить расчёт'}</button><div className="proposal-photos"><h3>Фото для предложения · {(q.photoUrls?.length||0)+localPhotos.length} / 9</h3><div className="proposal-photo-grid">{(q.photoUrls||[]).map((url,i)=><div key={url}><img src={photoProxy(url)} alt={'Фото автомобиля '+(i+1)}/><button aria-label={'Убрать фото '+(i+1)} onClick={()=>change('photoUrls',q.photoUrls.filter(x=>x!==url))}>×</button></div>)}{localPhotos.map((item,i)=><div key={item.id}><span>{item.blob.name}</span><button aria-label={'Убрать загруженное фото '+(i+1)} onClick={()=>setLocalPhotos(p=>p.filter(x=>x.id!==item.id))}>×</button></div>)}</div><label className="btn">Добавить фотографии<input hidden type="file" multiple accept="image/jpeg,image/png,image/webp" onChange={addProposalPhotos}/></label><small>До 9 фото, по 3 в ряд, на отдельной странице PDF. Фото с устройства используются в текущем предложении.</small></div><button className="btn" disabled={pdfBusy||importBusy} onClick={offer}><Download size={17}/>{pdfBusy?'Создаю PDF…':'Коммерческое предложение'}</button>{readOnly&&<p>Ваш доступ — только просмотр.</p>}<small>Сохранение расчёта не изменяет себестоимость автомобиля.</small></section><section className="panel encar-saved"><div className="panel-title"><h3>Сохранённые расчёты</h3><button className="icon-btn" aria-label="Обновить расчёты" onClick={list}><RefreshCw size={16}/></button></div>{!quotes.length?<p className="muted-text">Здесь появятся ваши расчёты.</p>:quotes.map(x=><button key={x.id} className={'encar-saved-item '+(q.id===x.id?'active':'')} onClick={()=>{setLocalPhotos([]);set(x);se('');sn('');squery('')}}><b>{x.brand} {x.model}</b><span>{x.year} · {fmt(x.result?.rub)} ₽</span><small>{new Date(x.updatedAt).toLocaleString('ru-RU')}</small></button>)}</section></aside></div></div>
}
