import React,{useState,useRef,useEffect} from 'react';
import {VIDEO_MAX_BYTES,compressVideo} from './video-compression.js';
export default function MediaUpload({car,category,upload,onDone,onBusy}){
 const video=category==='Видео',limit=video?VIDEO_MAX_BYTES:10*1024*1024;
 const [queue,set]=useState([]),[busy,bus]=useState(false),[error,err]=useState(''),[progress,prog]=useState('');
 const revision=useRef(car.revision),controller=useRef();const [compressing,sc]=useState(false);useEffect(()=>()=>controller.current?.abort(),[]);
 function select(files){err('');const list=Array.from(files||[]);if(list.some(f=>!f.size||(!video&&f.size>limit))){err('Каждый файл должен быть непустым и не более '+(video?30:10)+' МБ');set([]);return}set(list.map(file=>({file,id:crypto.randomUUID()})));}
 async function submit(e){e.preventDefault();if(!queue.length)return;bus(true);onBusy(true);err('');let done=0;try{for(const item of queue){if(video&&item.file.size>limit){sc(true);controller.current=new AbortController();try{item.file=await compressVideo(item.file,{signal:controller.current.signal,onProgress:prog});set(p=>p.map(x=>x.id===item.id?{...item}:x));}finally{sc(false)}}prog('Загрузка '+(done+1)+' из '+queue.length+': '+item.file.name);const saved=await upload(item,category,revision.current);revision.current=saved.revision;done++;set(p=>p.filter(x=>x.id!==item.id));}onDone(done);}catch(e){err('Сохранено: '+done+'. '+e.message+' Уже загруженные файлы повторно не добавятся.');}finally{bus(false);onBusy(false);prog('');}}
 return <form onSubmit={submit}><div className="modal-body"><label className="upload-zone"><strong>{video?'Выберите видео':'Выберите фотографии'}</strong><span>{video?'MP4, MOV, WEBM · до 30 МБ · большие файлы сжимаются автоматически':'JPG, PNG, WEBP · до 10 МБ на фото · можно выбрать несколько'}</span><input type="file" multiple={!video} accept={video?'.mp4,.mov,.webm':'.jpg,.jpeg,.png,.webp'} disabled={busy} onChange={e=>select(e.target.files)}/></label>{queue.length>0&&<ul className="upload-queue">{queue.map(x=><li key={x.id}>{x.file.name} · {(x.file.size/1024/1024).toFixed(1)} МБ{video&&x.file.size>limit?' · будет сжато':''}</li>)}</ul>}{progress&&<p role="status">{progress}</p>}{error&&<p className="error" role="alert">{error}</p>}<p className="fine-print">{video?'Видео больше 30 МБ сжимается на вашем устройстве перед отправкой. Не закрывайте вкладку. Качество может снизиться; исходный файл не изменяется. Для сжатия в браузере — исходные файлы до 512 МБ.':'Файлы загружаются по очереди. Дождитесь завершения перед закрытием окна.'}</p></div><div className="modal-foot">{compressing&&<button type="button" className="btn" onClick={()=>controller.current?.abort()}>Отменить сжатие</button>}<button className="btn primary" disabled={busy||!queue.length}>{busy?(compressing?'Сжимаю…':'Загружаю…'):video?'Загрузить видео':'Загрузить фото ('+queue.length+')'}</button></div></form>
}
export function CarVideos({car,onUpload,onDelete}){
 const videos=car.files.filter(f=>f.category==='Видео');
 return <section className="panel"><div className="panel-title"><h2>Видео · {videos.length}</h2><button className="btn primary" data-write="" onClick={onUpload}>＋ Добавить видео</button></div>{!videos.length?<p className="muted-text">Добавьте видео автомобиля отдельно от фотографий.</p>:<div className="video-grid">{videos.map(f=><article key={f.id}><video controls playsInline preload="metadata" src={'/api/cars/'+car.id+'/files/'+f.id}/><b>{f.name}</b><div className="video-actions"><a className="text-btn" href={'/api/cars/'+car.id+'/files/'+f.id} download={f.name}>Скачать</a><button className="text-btn" data-write="" onClick={()=>onDelete(f)}>Удалить</button></div></article>)}</div>}</section>
}
