import React,{useEffect,useRef,useState} from 'react';
import {Upload,RotateCcw,X,Loader2,ScanText,Check} from 'lucide-react';
import {checkPassportFiles,mergePassportFields} from './passport.js';

export default function PassportImport({role,car,onUpload,values,onValues,onFiles,onBusy,disabled,fieldLabels,onDetected}){
 const [pages,setPages]=useState([]),[running,setRunning]=useState(false),[error,setError]=useState(''),[result,setResult]=useState(null),[progress,setProgress]=useState({percent:0,message:''});
 const [conflicts,setConflicts]=useState({});const abortRef=useRef(),pagesRef=useRef([]),mounted=useRef(true);
 const [aiEnabled,setAiEnabled]=useState(null),[configError,setConfigError]=useState(false),[mode,setMode]=useState('ai');
 useEffect(()=>{mounted.current=true;const controller=new AbortController();fetch('/api/passport/config',{signal:controller.signal}).then(r=>{if(!r.ok)throw new Error();return r.json()}).then(d=>{if(mounted.current)setAiEnabled(d.enabled===true)}).catch(()=>{if(mounted.current&&!controller.signal.aborted)setConfigError(true)});return()=>{mounted.current=false;controller.abort();abortRef.current?.abort();pagesRef.current.forEach(p=>URL.revokeObjectURL(p.url))}},[]);
 useEffect(()=>{const saved=(car.files||[]).filter(f=>f.partyRole===role).slice(-3);if(!saved.length)return;let cancelled=false;Promise.all(saved.map(async f=>{const r=await fetch('/api/cars/'+car.id+'/files/'+f.id);if(!r.ok)throw new Error('Не удалось загрузить сохранённый паспорт');return new File([await r.blob()],f.name,{type:f.mime})})).then(files=>{if(cancelled)return;replacePages(files.map(file=>({file,url:URL.createObjectURL(file),rotation:0}))) }).catch(e=>{if(!cancelled)setError(e.message)});return()=>{cancelled=true}},[]);
 function replacePages(next){pagesRef.current=next;setPages(next);onFiles([]);setResult(null);setConflicts({});onDetected([]);}
 async function choose(e){const files=[...e.target.files];e.target.value='';if(!files.length)return;try{checkPassportFiles(files);onBusy(true);setRunning(true);await onUpload(files);pagesRef.current.forEach(p=>URL.revokeObjectURL(p.url));replacePages(files.map(file=>({file,url:URL.createObjectURL(file),rotation:0})));setError('')}catch(e){setError(e.message)}finally{onBusy(false);setRunning(false)}}
 function remove(index){URL.revokeObjectURL(pages[index].url);replacePages(pages.filter((_,i)=>i!==index))}
 async function recognize(nextMode='ai'){if(running||disabled)return;setMode(nextMode);setError('');setResult(null);setProgress({percent:nextMode==='ai'?null:0,message:'Подготовка распознавания…'});setRunning(true);onBusy(true);setConflicts({});const controller=new AbortController();abortRef.current=controller;
  try{const {recognizePassport}=nextMode==='ai'?await import('./passport-ai-client.js'):await import('./passport-ocr.js');if(controller.signal.aborted)return;
   const output=await recognizePassport(pages,{signal:controller.signal,onProgress:p=>mounted.current&&setProgress(p)});
   if(!mounted.current||controller.signal.aborted)return;const merged=mergePassportFields(values,output.fields);onValues(merged.values);onDetected(Object.keys(output.fields));setConflicts(merged.conflicts);setResult(output);
   if(!Object.keys(output.fields).length)setError('Поля не удалось распознать. Поверните фото, загрузите более чёткий снимок или заполните данные вручную.');
  }catch(e){if(mounted.current&&!controller.signal.aborted)setError(e.userMessage||e.message?.includes('слишком много времени')?e.message:'Не удалось распознать фото. Попробуйте ещё раз или заполните данные вручную.')}
  finally{if(mounted.current&&abortRef.current===controller){setRunning(false);onBusy(false)}}
 }
 return <section className="passport-import"><div className="passport-import-heading"><div><h3><ScanText size={18}/> Паспорт {role==='buyer'?'покупателя':'продавца'}</h3><p>Основной разворот и страница с пропиской. Для ID-карты — обе стороны.</p></div><label className={'btn passport-choose '+(disabled||running?'disabled':'')}><Upload size={16}/> {pages.length?'Выбрать другие фото':'Загрузить паспорт'}<input type="file" accept="image/jpeg,image/png,image/webp,application/pdf" multiple disabled={disabled||running} onChange={choose}/></label></div><p className="fine-print">До 3 файлов JPG, PNG, WEBP или PDF, суммарно до 10 МБ. Снимайте без бликов, текст должен быть крупным.</p>
 {!!pages.length&&<><div className="passport-pages">{pages.map((p,i)=><div className="passport-page" key={p.url}><div className="passport-preview">{p.file.type==='application/pdf'?<a href={p.url} target="_blank" rel="noreferrer">Открыть PDF</a>:<img src={p.url} style={{transform:`rotate(${p.rotation}deg)`}} alt={'Страница паспорта '+(i+1)}/>}</div><div><span>Фото {i+1}</span><button type="button" className="icon-btn" disabled={disabled||running} aria-label={'Повернуть фото '+(i+1)} onClick={()=>{const next=pages.map((x,n)=>n===i?{...x,rotation:(x.rotation+90)%360}:x);pagesRef.current=next;setPages(next)}}><RotateCcw size={16}/></button><button type="button" className="icon-btn" disabled={disabled||running} aria-label={'Убрать фото '+(i+1)} onClick={()=>remove(i)}><X size={16}/></button></div></div>)}</div><div className="passport-actions"><button type="button" className="btn primary" disabled={disabled||running||!aiEnabled} onClick={()=>recognize('ai')}>{running?<Loader2 size={16} className="spin"/>:<ScanText size={16}/>} {running&&mode==='ai'?'Распознавание…':'Распознать с AI'}</button><button type="button" className="btn" disabled={disabled||running||pages.some(p=>p.file.type==='application/pdf')} onClick={()=>recognize('local')}>Распознать на устройстве</button>{running&&<button className="btn" type="button" onClick={()=>{abortRef.current?.abort();setRunning(false);onBusy(false)}}>Остановить</button>}</div>{running&&<div className="ocr-progress" role="status"><progress max="100" value={progress.percent??undefined}/><span>{progress.message}{progress.percent!==null&&` ${progress.percent}%`}</span></div>}{!aiEnabled&&<p className="fine-print" role="status">{configError?'Не удалось проверить подключение AI. Откройте форму заново.':aiEnabled===null?'Проверяю подключение AI…':'AI-распознавание ещё не подключено. Пока доступны распознавание на устройстве и ручное заполнение.'}</p>}<p className="fine-print">При нажатии «Распознать с AI» фото передаются OpenAI для обработки. Распознавание на устройстве работает локально. Файлы уже сохранены в «Документах». Распознавание запускается только кнопкой. Заполненные данные сохраните кнопкой «Сохранить». PDF распознаётся через AI.</p></>}
 {result&&<div className="ocr-result" role="status"><Check size={16}/><span>Найдено полей: {Object.keys(result.fields).length}. {result.source==='openai'?'Распознано с AI. ':''}Проверьте выделенные значения по паспорту.</span></div>}
 {result?.warnings?.map(w=><p className="fine-print" key={w}>{w}</p>)}
 {!!Object.keys(conflicts).length&&<div className="ocr-conflicts"><b>Есть отличия от заполненных данных</b>{Object.entries(conflicts).map(([key,value])=><div key={key}><span>{fieldLabels[key]}: <strong>{value}</strong></span><button type="button" className="text-btn" onClick={()=>{onValues({...values,[key]:value});setConflicts(c=>{const n={...c};delete n[key];return n})}}>Использовать из паспорта</button></div>)}</div>}
 {error&&<div className="error" role="alert">{error}</div>}
 {result?.text&&<details className="ocr-text"><summary>Распознанный текст</summary><pre>{result.text}</pre></details>}
 </section>;
}
