import DocumentLink from './DocumentLink.jsx';
import React,{useState,useId,useEffect} from 'react';
import {Upload,FileText,Loader2,Trash2} from 'lucide-react';
import {PAYER_TYPES,PAYMENT_METHODS,PAYMENT_DOCUMENTS} from './payment.js';
export default function PaymentSection({car,api,onUpdate,onDelete,readOnly}){
 const [busy,setBusy]=useState(''),[error,setError]=useState('');const id=useId();const[contractAmount,setContractAmount]=useState(car.payment?.contractAmountRub??'');useEffect(()=>setContractAmount(car.payment?.contractAmountRub??''),[car.payment?.contractAmountRub,car.id]);
 async function change(key,value){setBusy(key);setError('');try{const saved=await api('/cars/'+car.id+'/payment',{method:'PATCH',body:{revision:car.revision,payment:{...car.payment,payerType:car.payment?.payerType||'',method:car.payment?.method||'',[key]:value}}});onUpdate(saved)}catch(e){setError(e.message)}finally{setBusy('')}}
 async function upload(type,e){const files=Array.from(e.target.files||[]);e.target.value='';if(!files.length)return;setBusy(type);setError('');let current=car;let count=0;try{for(const file of files){if(!file.size||file.size>10*1024*1024)throw new Error('Каждый файл должен быть непустым и не больше 10 МБ')}for(const file of files){const fd=new FormData();fd.set('file',file);fd.set('category',type.includes('договор')||type.includes('Договор')?'Договор':'Документ');fd.set('paymentDocument',type);fd.set('revision',current.revision);fd.set('uploadId',crypto.randomUUID());current=await api('/cars/'+car.id+'/files',{method:'POST',body:fd});onUpdate(current);count++}}catch(e){setError((count?'Сохранено файлов: '+count+'. ':'')+e.message)}finally{setBusy('')}}
 return <section className="panel payment-section"><div className="panel-title"><div><h2>Оплата</h2><p>Плательщик, способ оплаты и подтверждающие документы</p></div></div><div className="form-grid"><label htmlFor={id+'-payer'}>Плательщик<select id={id+'-payer'} disabled={readOnly||!!busy} value={car.payment?.payerType||''} onChange={e=>change('payerType',e.target.value)}><option value="">Не выбран</option>{PAYER_TYPES.map(x=><option key={x}>{x}</option>)}</select></label><label htmlFor={id+'-method'}>Способ оплаты<select id={id+'-method'} disabled={readOnly||!!busy} value={car.payment?.method||''} onChange={e=>change('method',e.target.value)}><option value="">Не выбран</option>{PAYMENT_METHODS.map(x=><option key={x}>{x}</option>)}</select></label><label htmlFor={id+'-amount'}>Сумма в договоре, ₽<input id={id+'-amount'} type="number" min="0" step="0.01" disabled={readOnly||!!busy} value={contractAmount} onChange={e=>setContractAmount(e.target.value)}/><button type="button" className="btn" disabled={readOnly||!!busy||String(contractAmount)===String(car.payment?.contractAmountRub??'')} onClick={()=>change('contractAmountRub',contractAmount)}>Сохранить сумму</button></label></div><div className="payment-documents">{PAYMENT_DOCUMENTS.map(type=><div className="payment-document" key={type}><div className="party-heading"><h3><FileText size={17}/> {type}</h3>{!readOnly&&<label className={'btn passport-choose '+(busy?'disabled':'')}>{busy===type?<Loader2 size={16} className="spin"/>:<Upload size={16}/>} {busy===type?'Загрузка…':'Загрузить'}<input type="file" multiple accept=".pdf,.jpg,.jpeg,.png,.webp,.doc,.docx,.xls,.xlsx,.txt,.csv" disabled={!!busy} onChange={e=>upload(type,e)}/></label>}</div>{car.files.filter(f=>f.paymentDocument===type).map(f=><div className="passport-saved-file" key={f.id}><DocumentLink car={car} file={f}/>{!readOnly&&<button type="button" className="icon-btn" aria-label={'Удалить '+f.name} disabled={!!busy} onClick={()=>onDelete(f)}><Trash2 size={16}/></button>}</div>)}{!car.files.some(f=>f.paymentDocument===type)&&<p className="fine-print">Файлы пока не загружены</p>}</div>)}</div><p className="fine-print">Выбор сохраняется автоматически. Можно загрузить несколько файлов, до 10 МБ каждый. Все файлы также доступны в документах автомобиля.</p>{error&&<p className="error" role="alert">{error}</p>}</section>
}
