import React,{useState,useEffect} from 'react';
import {FILE_TYPES} from './domain.js';
import './telegram.css';
const labels={year:'Год',mileage:'Пробег',price:'Цена продажи, ₽',location:'Местонахождение',status:'Статус',color:'Цвет',trim:'Комплектация'};
const states={queued:'Ожидает разбора',reading:'Распознаётся',pending:'На проверке',error:'Нужна проверка',saving:'Сохраняется',done:'Добавлено',skipped:'Пропущено'};
function Proposal({job,cars,api,reload,onSaved}){
 const [carId,setCar]=useState(job.carId||''),[values,setValues]=useState(job.extraction?.fields||{}),[summary,setSummary]=useState(job.extraction?.summary||''),[files,setFiles]=useState(job.attachments||[]),[dirty,setDirty]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const editable=!!job.extraction&&!['done','skipped','reading','saving'].includes(job.state),car=cars.find(c=>c.id===carId);
 async function run(action,body={}){setBusy(true);setError('');try{const r=await api('/telegram/intake/'+job.id+'/'+action,{method:'POST',body});if(r.car)onSaved(r.car);await reload();setDirty(false)}catch(e){setError(e.message)}finally{setBusy(false)}}
 return <article className="panel intake-job"><div className="panel-title"><h3>{job.carLabel||job.groupTitle}</h3><span>{states[job.state]}</span></div><p className="avito-note">{job.groupTitle} · {new Date(job.createdAt).toLocaleString('ru-RU')}</p>
 {job.error&&<p className="error">{job.error}</p>}{job.notificationError&&<p className="error">{job.notificationError}</p>}{job.sourceTexts&&<details><summary>Исходные сообщения</summary>{job.sourceTexts.map(m=><p key={m.messageId} style={{whiteSpace:'pre-wrap'}}>{m.text}{m.replyText?'\nВ ответ на: '+m.replyText:''}</p>)}</details>}
 {job.extraction&&<><label>Карточка автомобиля<select disabled={!editable||busy} value={carId} onChange={e=>{setCar(e.target.value);setDirty(true)}}><option value="">Выберите автомобиль</option>{cars.filter(c=>!c.archived).map(c=><option value={c.id} key={c.id}>{c.brand} {c.model} · {c.vin||'без VIN'} · {c.owner||''}</option>)}</select></label><p className="avito-note">{job.extraction.vin?'VIN из материалов: '+job.extraction.vin:'Полный VIN не найден — карточку нужно выбрать вручную.'}</p>
 <label>Сводка для заметок<textarea rows={4} maxLength={3000} disabled={!editable||busy} value={summary} onChange={e=>{setSummary(e.target.value);setDirty(true)}}/></label>
 {!!Object.keys(values).length&&<div className="intake-fields">{Object.entries(values).map(([k,v])=><label key={k}>{labels[k]}<small>Сейчас: {String(car?.[k]??'не указано')}</small><input disabled={!editable||busy} type={['year','mileage','price'].includes(k)?'number':'text'} value={v} onChange={e=>{setValues(x=>({...x,[k]:e.target.type==='number'?e.target.value===''?'':Number(e.target.value):e.target.value}));setDirty(true)}}/>{editable&&<button className="text-btn" disabled={busy} onClick={()=>{setValues(x=>{const y={...x};delete y[k];return y});setDirty(true)}}>Не менять это поле</button>}</label>)}</div>}
 {files.map((f,i)=><label key={f.uniqueId}><a href={'/api/telegram/intake/'+job.id+'/file/'+encodeURIComponent(f.uniqueId)} target="_blank" rel="noreferrer">{f.name} ↗</a><select disabled={!editable||busy} value={f.category} onChange={e=>{setFiles(x=>x.map((v,n)=>n===i?{...v,category:e.target.value}:v));setDirty(true)}}>{FILE_TYPES.map(t=><option key={t}>{t}</option>)}</select></label>)}
 </>}
 <div className="avito-actions">{editable&&<><button className="btn" disabled={busy||!carId} onClick={()=>run('prepare',{carId,summary,fields:values,attachments:files})}>Обновить предпросмотр</button><button className="btn primary" disabled={busy||dirty||!job.carId||job.state!=='pending'} onClick={()=>run('apply',{version:job.version})}>Добавить в карточку</button></>}{!['done','skipped','saving'].includes(job.state)&&<button className="btn" disabled={busy||(job.state==='reading'&&job.startedAt>Date.now()-90000)} onClick={()=>run('read')}>Разобрать ещё раз</button>}{editable&&<button className="btn" disabled={busy} onClick={()=>run('skip')}>Пропустить</button>}</div>
 {dirty&&<p className="avito-note">Обновите предпросмотр, затем проверьте и подтвердите сохранение.</p>}{busy&&<p role="status">Обрабатываю…</p>}{error&&<p className="error" role="alert">{error}</p>}</article>
}
export default function TelegramIntake({api,cars,onSaved}){
 const [data,setData]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[pair,setPair]=useState('');
 async function reload(){setData(await api('/telegram/intake'))}
 useEffect(()=>{reload().catch(e=>setError(e.message))},[]);
 async function run(fn){setBusy(true);setError('');try{await fn();await reload()}catch(e){setError(e.message)}finally{setBusy(false)}}
 return <div className="avito-module intake-module"><section className="panel"><div className="panel-title"><h2>Из рабочих групп</h2><button className="btn" disabled={busy} onClick={()=>run(reload)}>Обновить</button></div><p>Фото, документы и данные из Telegram. Карточки меняются только после вашего подтверждения.</p>
 <p>{data?.paired?'Личный чат подключён · @'+data.botUsername:'Сначала привяжите личный чат для подтверждений.'}</p><button className="btn primary" disabled={busy} onClick={()=>run(async()=>{const r=await api('/telegram/intake/connect',{method:'POST',body:{}});setPair(r.url)})}>{busy?'Подключаю…':data?.paired?'Перепривязать личный чат':'Подключить приём из групп'}</button>
 {pair&&<p><a className="btn" href={pair} target="_blank" rel="noreferrer">Открыть бота и нажать «Запустить» ↗</a><small>Ссылка действует 10 минут. Не пересылайте её другим.</small></p>}
 <ol><li>Откройте бота по кнопке выше и нажмите «Запустить».</li><li>Добавьте этого бота администратором рабочей группы.</li><li>От своего аккаунта отправьте в группе <code>/vector_on</code>.</li><li>Отправьте новые материалы с VIN. Бот пришлёт предложение в личку.</li></ol><p className="avito-note">Старые сообщения не загружаются. Для альбома добавьте VIN в подпись; для отдельного документа — в подпись или сообщение, на которое отвечаете. Если VIN не определён, выберите карточку здесь. Вложения до 10 МБ каждое; изображения и PDF распознаются при подключённом OpenAI. Расходы и валюты сохраняются в сводке, без автоматического пересчёта себестоимости.</p>
 {data&&!data.aiEnabled&&<p className="error">OpenAI не подключён: доступны исходный текст, поиск по полному VIN и ручная проверка категорий.</p>}
 {data?.groups.map(g=><div className="panel-title" key={g.id}><span>{g.title} · {g.enabled?'Приём включён':'Приём выключен'}</span><button className="btn" disabled={busy} onClick={()=>run(()=>api('/telegram/intake/group',{method:'POST',body:{id:g.id,enabled:!g.enabled}}))}>{g.enabled?'Отключить':'Включить'}</button></div>)}{error&&<p className="error" role="alert">{error}</p>}</section>
 {data?.jobs.length===0&&<section className="panel"><h3>Пока нет материалов</h3><p>Подключите группу и отправьте новое сообщение с VIN автомобиля.</p></section>}
 {data?.jobs.map(j=><Proposal key={j.id+':'+j.version+':'+j.state} job={j} cars={cars} api={api} reload={reload} onSaved={onSaved}/>)}
 </div>
}
