import React,{useState,useEffect,useRef} from 'react';
import AdDraftDialog from './AdDraftDialog.jsx';
import {Send,Eye,Save,RefreshCw,Sparkles,ArrowUp,ArrowDown,X,Loader2,ExternalLink} from 'lucide-react';
import {TELEGRAM_CHANNEL,TELEGRAM_URL,telegramDraft,telegramPhotos,telegramText} from './telegram.js';
import './avito.css';
import './telegram.css';
const states={published:'Опубликовано',sending:'Отправка не завершена',updating:'Обновление не завершено',failed:'Не отправлено',unknown:'Нужно проверить канал',partial:'Опубликована часть поста',update_failed:'Не удалось обновить',update_unknown:'Проверьте обновление в канале'};
function Preview({value,onClose,onConfirm,disabled,busy,error}){
 const ref=useRef();useEffect(()=>{const old=document.activeElement;ref.current.showModal();return()=>old?.focus?.()},[]);
 return <dialog ref={ref} className="modal wide telegram-dialog" onCancel={e=>{e.preventDefault();if(!busy)onClose();}}><div className="modal-head"><div><h2>{value.operation==='update'?'Обновить пост':'Публикация в Telegram'}</h2><p>@{value.snapshot.channel}</p></div><button className="icon-btn" aria-label="Закрыть" disabled={busy} onClick={onClose}><X size={20}/></button></div><div className="modal-body"><div className="telegram-preview"><div className="telegram-preview-label">Бум Авто</div>{value.operation==='publish'&&<><div className="telegram-preview-images">{value.snapshot.photos.map(p=><img key={p.id} src={'/api/cars/'+value.snapshot.carId+'/files/'+p.id} alt="Фото для публикации"/>)}</div><p className="telegram-preview-caption">{value.snapshot.title}</p><p className="avito-note">Фотографии отправятся альбомом. Далее — отдельное сообщение:</p></>}<p className="telegram-preview-text">{value.snapshot.text}</p></div>{disabled&&<p className="avito-note">Для отправки сначала подключите бота и проверьте его доступ к каналу.</p>}{error&&<p className="error" role="alert">{error}</p>}</div><div className="modal-foot"><button className="btn" disabled={busy} onClick={onClose}>Отмена</button><button className="btn primary" disabled={disabled||busy} onClick={onConfirm}>{busy?<Loader2 size={17} className="spin"/>:<Send size={17}/>} {value.operation==='update'?'Обновить пост в канале':'Опубликовать в канал'}</button></div></dialog>;
}
export default function Telegram({car,api,onSaved,readOnly,isOwner}){
 const [aiError,setAIError]=useState(''),[applied,setApplied]=useState(false);
 const [connectionError,setConnectionError]=useState(''),[connectionChecked,setConnectionChecked]=useState(false);
 const [v,setV]=useState(()=>telegramDraft(car)),[post,setPost]=useState(null),[config,setConfig]=useState(null),[busy,setBusy]=useState(''),[error,setError]=useState(''),[preview,setPreview]=useState(null),[proposal,setProposal]=useState(null);
 const lock=useRef(false),alive=useRef(true);useEffect(()=>{alive.current=true;refresh().catch(e=>alive.current&&setConnectionError(e.message));return()=>{alive.current=false;}},[]);
 async function refresh(){const r=await api('/cars/'+car.id+'/telegram');if(alive.current){setPost(r.post);setConfig(r.config);}}
 const photos=telegramPhotos(car),dirty=JSON.stringify(v)!==JSON.stringify(telegramDraft(car)),frozen=!!post?.sentPhotos?.length,canUpdate=post?.hasText&&['published','update_failed','update_unknown'].includes(post.state),canPublish=!post||post.state==='failed';
 const disabled=readOnly||!!busy;
 const change=(k,value)=>{setV(x=>({...x,[k]:value}));setPreview(null);};
 async function run(label,fn,onError){if(lock.current)return;lock.current=true;setBusy(label);setError('');try{await fn();}catch(e){if(alive.current){if(onError)onError(e.message);else setError(e.message);}}finally{lock.current=false;if(alive.current)setBusy('');}}
 async function checkConnection(){setConnectionError('');setConnectionChecked(false);await run('Проверяю подключение…',async()=>{const r=await api('/telegram/check',{method:'POST',body:{}});if(alive.current){setConfig(r);setConnectionChecked(true);}},setConnectionError);}
 async function save(e){e.preventDefault();await run('Сохраняю черновик…',async()=>onSaved(await api('/cars/'+car.id+'/telegram',{method:'PATCH',body:{...v,revision:car.revision}})));}
 function move(id,d){const ids=[...v.photoIds],i=ids.indexOf(id),j=i+d;if(j<0||j>=ids.length)return;[ids[i],ids[j]]=[ids[j],ids[i]];change('photoIds',ids);}
 async function showPreview(operation){await run('Готовлю предпросмотр…',async()=>{const p=await api('/cars/'+car.id+'/telegram/preview',{method:'POST',body:{revision:car.revision,operation}});if(alive.current)setPreview(p);});}
 async function publish(){const p=preview;await run(p.operation==='update'?'Обновляю пост…':'Отправляю пост…',async()=>{const r=await api('/cars/'+car.id+'/telegram/'+p.operation,{method:'POST',body:{revision:car.revision,previewId:p.id,confirm:p.operation}});if(alive.current){setPreview(null);setPost(r.post);setError(r.warning||'');if(r.car)onSaved(r.car);}});}
 async function generate(){setAIError('');setApplied(false);await run('Готовлю описание…',async()=>{const r=await api('/cars/'+car.id+'/telegram/generate',{method:'POST',body:{revision:car.revision}});if(alive.current)setProposal(r.description.slice(0,3000));},setAIError);}
 return <div className="avito-module telegram-module">
  <section className="panel avito-heading"><div><div className="avito-eyebrow"><Send size={18}/> TELEGRAM</div><h2>Пост об автомобиле</h2><a href={TELEGRAM_URL} target="_blank" rel="noreferrer">@{TELEGRAM_CHANNEL} <ExternalLink size={14}/></a></div><span className={'avito-state '+(post?.state==='published'?'published':'')}>{post?states[post.state]||'Нужно проверить':'Черновик'}</span></section>
  <section className="panel telegram-connection"><div><b>{config?.connected?'Бот подключён':config?.tokenPresent?'Требуется проверить бота':'Бот ещё не подключён'}</b><p className="avito-note">{config?.connected?'@'+config.botUsername+' · публикация доступна владельцу CRM':'Черновики и предпросмотр можно подготовить заранее.'}</p></div>{isOwner&&<button className="btn" disabled={!!busy||!config?.tokenPresent} type="button" onClick={checkConnection}>{busy==='Проверяю подключение…'?<Loader2 size={16} className="spin"/>:<RefreshCw size={16}/>} {busy==='Проверяю подключение…'?'Проверяю подключение…':'Проверить подключение'}</button>}{busy==='Проверяю подключение…'&&<p className="telegram-connection-result" role="status">Проверяем токен бота, канал и право публикации…</p>}{connectionError&&<div className="error telegram-connection-result" role="alert">{connectionError}</div>}{connectionChecked&&config?.connected&&<p className="telegram-connection-result telegram-connection-ok" role="status">Подключение проверено. Бот может публиковать в @{TELEGRAM_CHANNEL}.</p>}{isOwner&&!config?.connected&&<details className="telegram-setup"><summary>Как подключить</summary><ol><li>Создайте бота в <a href="https://t.me/BotFather" target="_blank" rel="noreferrer">@BotFather</a> командой /newbot.</li><li>Добавьте его администратором @boom_avto_vrn с правом публикации сообщений.</li><li>В настройках сайта добавьте секрет TELEGRAM_BOT_TOKEN и сохраните токен бота. Затем примените настройки обновлением сайта.</li><li>Нажмите «Проверить подключение». Эта проверка не отправляет сообщения.</li></ol></details>}</section>
  <form className="avito-form" onSubmit={save}><fieldset disabled={disabled}>
   <section className="panel"><div className="panel-title"><h3>Текст объявления</h3><button type="button" className="btn" disabled={disabled||!config?.aiEnabled} onClick={generate}>{busy==='Готовлю описание…'?<Loader2 size={16} className="spin"/>:<Sparkles size={16}/>} {busy==='Готовлю описание…'?'Готовлю описание…':'Помочь с описанием'}</button></div>{aiError&&<p className="error ad-generation-error" role="alert">{aiError}</p>}{applied&&<p className="ad-generation-applied" role="status">Текст добавлен в форму. Сохраните черновик.</p>}<label className="field"><span>Описание</span><textarea rows={8} maxLength={3000} value={v.description} onChange={e=>change('description',e.target.value)}/></label><label className="field"><span>Контакт для покупателей</span><input value={v.contact} maxLength={300} placeholder="Телефон или @username менеджера" onChange={e=>change('contact',e.target.value)}/></label><p className="avito-note">Характеристики и цена добавятся из карточки. Данные покупателя, продавца и внутренние документы в пост не попадут.</p><label className="telegram-sold"><input type="checkbox" checked={v.sold} onChange={e=>change('sold',e.target.checked)}/> Отметить «Продано» в тексте поста</label><p className="avito-note">Пост изменится только после предпросмотра и подтверждения обновления. AI использует баланс подключённого OpenAI API.</p></section>
   <section className="panel"><div className="panel-title"><h3>Фотографии · {v.photoIds.length} / 10</h3><button type="button" className="text-btn" disabled={frozen||!photos.length} onClick={()=>change('photoIds',photos.slice(0,10).map(p=>p.id))}>Выбрать первые 10</button></div><p className="avito-note">{frozen?'Альбом уже отправлен. Здесь можно обновить текст и цену; состав опубликованного альбома сохраняется.':'Первое фото станет обложкой альбома. JPG и PNG, до 10 МБ на фото и 25 МБ на отправку.'}</p>{!photos.length&&<p>Добавьте JPG или PNG в раздел «Фото» автомобиля.</p>}<div className="avito-photos">{photos.slice().sort((a,b)=>(v.photoIds.includes(a.id)?v.photoIds.indexOf(a.id):100)-(v.photoIds.includes(b.id)?v.photoIds.indexOf(b.id):100)).map(p=>{const i=v.photoIds.indexOf(p.id);return <article className={i>=0?'selected':''} key={p.id}><label><img src={'/api/cars/'+car.id+'/files/'+p.id} alt={p.name} loading="lazy"/><span><input type="checkbox" checked={i>=0} disabled={frozen||(i<0&&v.photoIds.length>=10)} onChange={e=>change('photoIds',e.target.checked?[...v.photoIds,p.id]:v.photoIds.filter(id=>id!==p.id))}/>{i===0?'Обложка':i>0?'Фото '+(i+1):'Выбрать'}</span></label>{i>=0&&!frozen&&<div className="avito-photo-actions"><button type="button" title="Раньше" disabled={!i} onClick={()=>move(p.id,-1)}><ArrowUp size={16}/></button><button type="button" title="Позже" disabled={i===v.photoIds.length-1} onClick={()=>move(p.id,1)}><ArrowDown size={16}/></button></div>}</article>})}</div></section>
   <div className="avito-savebar"><span>{dirty?'Есть несохранённые изменения':'Черновик сохранён'}</span><button type="submit" className="btn primary"><Save size={17}/> Сохранить черновик</button></div>
  </fieldset></form>
  {proposal!==null&&<AdDraftDialog channel="Telegram" description={proposal} disabled={disabled} onClose={()=>setProposal(null)} onApply={()=>{change('description',proposal);setProposal(null);setApplied(true);}}/>}
  <section className="panel"><h3>{canUpdate?'Обновление опубликованного поста':'Предпросмотр и публикация'}</h3><p className="avito-note">Текст поста: {telegramText(car,v).text.length} / 4096 символов. Публикация выполняется только после подтверждения владельцем.</p><div className="avito-actions">{isOwner&&canPublish&&<button className="btn primary" disabled={disabled||dirty} onClick={()=>showPreview('publish')}><Eye size={17}/> Предпросмотр</button>}{isOwner&&canUpdate&&<button className="btn primary" disabled={disabled||dirty} onClick={()=>showPreview('update')}><Eye size={17}/> Предпросмотр обновления</button>}<button className="btn" disabled={!!busy} onClick={()=>run('Проверяю статус…',refresh)}><RefreshCw size={17}/> Обновить статус</button>{post?.url&&<a className="btn" href={post.textUrl||post.url} target="_blank" rel="noreferrer">Открыть пост ↗</a>}</div>{dirty&&<p className="avito-note">Сначала сохраните изменения.</p>}{post?.postedAt&&<p className="avito-note">Опубликовано: {new Date(post.postedAt).toLocaleString('ru-RU')}</p>}{post&&['partial','unknown','sending','updating','update_unknown'].includes(post.state)&&<p className="avito-warning">Проверьте канал перед дальнейшими действиями. Автоматическая повторная публикация отключена, чтобы не создавать копии. Если отправлена только часть поста, оставшийся текст можно добавить вручную в канале.</p>}{post?.error&&<p className="error">{post.error}</p>}</section>
  {error&&<div className="error" role="alert">{error}</div>}{busy&&<div className="avito-progress" role="status"><Loader2 size={17} className="spin"/>{busy}</div>}
  {preview&&<Preview value={preview} onClose={()=>setPreview(null)} onConfirm={publish} disabled={!config?.connected||!isOwner} busy={!!busy} error={error}/>}
 </div>;
}
