import React,{useState,useEffect,useRef} from 'react';
import {Sparkles,Send,ChevronDown,ChevronUp,Loader2,Mic,Square,ArrowUpRight,LockKeyhole} from 'lucide-react';
import './assistant.css';
import './assistant-search.css';
export default function VectorSearch({cars,api,onOpen}){
 const [expanded,expand]=useState(false),[text,setText]=useState(''),[carId,setCarId]=useState(''),[messages,setMessages]=useState([]),[error,setError]=useState(''),[busy,setBusy]=useState(''),[recording,setRecording]=useState(false);
 const bottom=useRef(),input=useRef(),recorder=useRef(),stream=useRef(),timer=useRef(),alive=useRef(true),locked=useRef(false);
 useEffect(()=>{alive.current=true;api('/assistant').then(s=>alive.current&&setMessages(s.messages)).catch(e=>alive.current&&setError(e.message));return()=>{alive.current=false;clearTimeout(timer.current);if(recorder.current?.state==='recording')recorder.current.stop();stream.current?.getTracks().forEach(t=>t.stop());};},[]);
 useEffect(()=>{if(expanded)bottom.current?.scrollIntoView({block:'nearest',behavior:'smooth'});},[messages.length,expanded]);
 async function ask(question=text,selected=carId){if(locked.current||recording||!question.trim())return;locked.current=true;setBusy('search');expand(true);setError('');try{const s=await api('/assistant/search',{method:'POST',body:{message:question,carId:selected}});if(alive.current){setMessages(s.messages);setText('');}}catch(e){if(alive.current){setError(e.message);try{const s=await api('/assistant');if(alive.current)setMessages(s.messages);}catch{}}}finally{if(alive.current)setBusy('');locked.current=false;}}
 async function voice(){
  if(recording){recorder.current?.stop();return;}if(locked.current)return;
  if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder){setError('Используйте диктовку на клавиатуре телефона: браузер не поддерживает запись.');return;}
  locked.current=true;setBusy('microphone');setError('');
  try{const media=await navigator.mediaDevices.getUserMedia({audio:true});if(!alive.current){media.getTracks().forEach(t=>t.stop());return;}stream.current=media;const mime=['audio/webm;codecs=opus','audio/mp4','audio/webm'].find(t=>MediaRecorder.isTypeSupported(t));const rec=new MediaRecorder(media,mime?{mimeType:mime}:undefined),parts=[];let failed=false;recorder.current=rec;rec.ondataavailable=e=>e.data.size&&parts.push(e.data);
   rec.onerror=()=>{failed=true;if(rec.state==='recording')rec.stop();};
   rec.onstop=async()=>{clearTimeout(timer.current);media.getTracks().forEach(t=>t.stop());if(!alive.current)return;setRecording(false);if(failed){setError('Не удалось записать голос. Напишите вопрос.');return;}locked.current=true;setBusy('voice');try{const type=rec.mimeType||'audio/webm',fd=new FormData();fd.set('audio',new File(parts,type.includes('mp4')?'voice.m4a':'voice.webm',{type}));const s=await api('/assistant/transcribe',{method:'POST',body:fd});if(alive.current){setText(old=>(old?old+' ':'')+s.text);input.current?.focus();}}catch(e){if(alive.current)setError(e.message);}finally{locked.current=false;if(alive.current)setBusy('');}};
   rec.start();setRecording(true);expand(true);locked.current=false;setBusy('');timer.current=setTimeout(()=>{if(rec.state==='recording')rec.stop();},60000);
  }catch{stream.current?.getTracks().forEach(t=>t.stop());locked.current=false;setBusy('');setError('Разрешите доступ к микрофону или напишите вопрос.');}
 }
 return <section className="vector-ai" aria-label="Поиск VECTOR AI"><header className="vai-heading"><div className="vai-brand"><span className="vai-mark"><Sparkles size={21}/></span><div><h2>VECTOR <span>AI</span></h2><p>Поиск по данным CRM</p></div></div><div className="vai-header-actions"><span className="vai-readonly"><LockKeyhole size={14}/> Только чтение</span><button type="button" className="btn vai-expand" onClick={()=>expand(x=>!x)} aria-expanded={expanded}>{expanded?'Свернуть':'Диалог'}{expanded?<ChevronUp size={16}/>:<ChevronDown size={16}/>}</button></div></header>
 {expanded&&<div className="vai-dialogue"><div className="vai-messages" role="log" aria-label="Вопросы и ответы" aria-live="polite">{messages.length?messages.map((m,i)=><div className={'vai-message '+m.role} key={i}><small>{m.role==='user'?'Вы':m.engine==='database'?'VECTOR · данные CRM':'VECTOR AI'}</small><p>{m.text}</p>
 {m.sources?.length>0&&<div className="vai-sources"><span>Источники</span>{m.sources.map(s=><button type="button" key={s.id} disabled={!cars.some(c=>c.id===s.carId)} onClick={()=>{const c=cars.find(c=>c.id===s.carId);if(c)onOpen(c,s.section);}}>{s.carLabel} · {s.label}<ArrowUpRight size={14}/></button>)}</div>}
 {m.choices?.length>0&&<div className="vai-choices">{m.choices.map(c=><button type="button" className="btn" disabled={!!busy||recording} key={c.id} onClick={()=>{setCarId(c.id);ask(m.question,c.id);}}>{c.label}{c.owner?' · '+c.owner:''}</button>)}</div>}
 {m.checkedAt&&<small className="vai-checked">По состоянию на {new Date(m.checkedAt).toLocaleString('ru-RU',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'})}</small>}</div>):<p className="vai-empty">Спросите о маршруте, датах, цене, расходах или документах автомобиля.</p>}{busy==='search'&&<p className="vai-progress"><Loader2 className="spin" size={17}/> Ищу в разделах карточки…</p>}<div ref={bottom}/></div></div>}
 <form className="vai-composer" onSubmit={e=>{e.preventDefault();ask();}}><label className="vai-car-select"><span>Автомобиль</span><select disabled={!!busy||recording} value={carId} onChange={e=>setCarId(e.target.value)}><option value="">Найти по вопросу или VIN</option>{cars.map(c=><option key={c.id} value={c.id}>{c.brand} {c.model} · {c.vin?c.vin.slice(-6):'без VIN'}{c.owner?' · '+c.owner:''}{c.archived?' · архив':''}</option>)}</select></label>
 <textarea ref={input} rows={2} maxLength={6000} disabled={!!busy||recording} value={text} onChange={e=>setText(e.target.value)} placeholder="Например: когда BMW 740d прибыл в Воронеж?" aria-label="Вопрос о данных CRM" onKeyDown={e=>{if(e.key==='Enter'&&(e.metaKey||e.ctrlKey)){e.preventDefault();ask();}}}/>
 {!messages.length&&<div className="vai-examples">{['Покажи маршрут автомобиля','Когда автомобиль прибыл в Бишкек?','Какая себестоимость автомобиля?'].map(q=><button type="button" key={q} disabled={!!busy||recording} onClick={()=>{setText(q);input.current?.focus();}}>{q}</button>)}</div>}
 {error&&<div className="error" role="alert">{error}</div>}<div className="vai-composer-bottom"><button type="button" className={'btn '+(recording?'danger':'')} disabled={!!busy} onClick={voice}>{recording?<Square size={17}/>:<Mic size={17}/>} {recording?'Стоп':'Голос'}</button><button className="btn primary" disabled={!!busy||recording||!text.trim()}>{busy?<Loader2 size={17} className="spin"/>:<Send size={17}/>} {busy==='voice'?'Распознаю…':'Спросить'}</button></div><p className="vai-fine">{recording?'Идёт запись, до 60 секунд. Нажмите «Стоп», затем проверьте текст.':'Редактирование и загрузка файлов через AI отключены. Для сложных вопросов данные CRM передаются в OpenAI. Содержимое PDF и сканов автоматически не читается.'}</p></form></section>;
}
