// Curated shortcuts for an import-car workspace, not a live sales ranking.
// First ten models are shortcuts; the remainder is sorted by the picker.
export const POPULAR_BRANDS=['Mercedes-Benz','BMW','Toyota','Lexus','Porsche','Li Auto','Zeekr','Changan','Hyundai','Kia'];
export const MODELS={
 'Mercedes-Benz':['G-Class','GLE','GLS','E-Class','C-Class','S-Class','GLC','CLA','GLA','V-Class','A-Class','AMG GT','B-Class','CL','CLK','CLS','EQA','EQB','EQC','EQE','EQS','GL','GLB','GLK','ML','R-Class','SL','SLC','SLK','Viano','Vito'],
 BMW:['X5','X7','X3','X6','5 Series','3 Series','X1','4 Series','7 Series','X4','1 Series','2 Series','6 Series','8 Series','i3','i4','i5','i7','i8','iX','iX1','iX2','iX3','M2','M3','M4','M5','M6','M8','X2','XM','Z3','Z4'],
 Toyota:['Camry','RAV4','Land Cruiser','Land Cruiser Prado','Corolla','Highlander','Alphard','Crown','Hilux','Sienna','4Runner','Auris','Avensis','Avalon','bZ4X','C-HR','Caldina','Celica','Century','Corolla Cross','Fortuner','Harrier','Hiace','Mark II','Mirai','Noah','Prius','Raize','Sequoia','Supra','Tacoma','Tundra','Vellfire','Venza','Vitz','Voxy','Yaris'],
 Lexus:['RX','NX','LX','ES','GX','IS','LS','UX','LM','GS','CT','HS','LBX','LC','LFA','RC','RZ','SC','TX'],
 Porsche:['Cayenne','Macan','Panamera','911','Taycan','718 Cayman','718 Boxster','Cayman','Boxster','Cayenne Coupe','924','928','944','968','Carrera GT'],
 'Li Auto':['L9','L7','L6','L8','MEGA','ONE','i8','i6'],
 Zeekr:['001','7X','009','X','007','7GT','9X'],
 Changan:['UNI-K','UNI-V','CS55 Plus','CS75 Plus','UNI-T','CS35 Plus','Q07','Hunter Plus','Eado Plus','Lamore','Alsvin','Benben','CS15','CS35','CS55','CS75','CS85','CS95','Eado','Hunter','Q05','Qiyuan A05','Qiyuan A07','Raeton'],
 Hyundai:['Tucson','Santa Fe','Palisade','Sonata','Elantra','Solaris','Creta','Staria','Grandeur','Kona','Accent','Avante','Bayon','Casper','Equus','Getz','H-1','i10','i20','i30','i40','Ioniq','Ioniq 5','Ioniq 6','ix35','ix55','Nexo','Porter','Starex','Terracan','Veloster','Venue','Veracruz'],
 Kia:['Sportage','Sorento','K5','Carnival','Seltos','K8','Rio','Cerato','Mohave','Telluride','Carens','Ceed','EV3','EV4','EV5','EV6','EV9','Forte','K3','K4','K7','K9','Magentis','Niro','Opirus','Optima','Picanto','Quoris','Ray','Soul','Stinger','Stonic','Venga','XCeed'],
 Audi:['Q7','Q8','Q5','A6','A4','A8','Q3','A5','RS6','e-tron','A1','A2','A3','A7','Q2','Q4 e-tron','Q6 e-tron','R8','RS3','RS4','RS5','RS7','RS Q8','S3','S4','S5','S6','S7','S8','SQ5','SQ7','SQ8','TT'],
 Volkswagen:['Tiguan','Touareg','Passat','Golf','Polo','Teramont','Multivan','Jetta','ID.4','ID.6','Amarok','Arteon','Atlas','Beetle','Bora','Caddy','Caravelle','CC','ID.3','ID.5','ID.7','ID. Buzz','Lavida','Lupo','Phaeton','Sagitar','Scirocco','Sharan','T-Cross','T-Roc','Taos','Tayron','Touran','Transporter','Vento'],
 Geely:['Monjaro','Coolray','Atlas','Tugella','Okavango','Preface','Emgrand','Cityray','EX5','Galaxy E8','Atlas Pro','Boyue','Emgrand GT','Emgrand X7','Galaxy L6','Galaxy L7','Geometry C','MK','Vision'],
 Haval:['Jolion','F7','H9','Dargo','H6','F7x','H3','M6','H5','H2','H4','H8'],
 Chery:['Tiggo 7 Pro Max','Tiggo 8 Pro Max','Tiggo 4 Pro','Tiggo 7 Pro','Tiggo 8 Pro','Arrizo 8','Tiggo 9','Tiggo 4','Tiggo 8','Tiggo 7','Amulet','Arrizo 5','Arrizo 6','Bonus','CrossEastar','Fora','IndiS','Kimo','QQ','Tiggo 2','Tiggo 3','Very'],
 Nissan:['Qashqai','X-Trail','Patrol','Murano','Teana','Serena','Note','Leaf','Juke','Altima','Almera','Ariya','Armada','Bluebird','Elgrand','Frontier','GT-R','Kicks','Maxima','Micra','Navara','Pathfinder','Primera','Rogue','Sentra','Skyline','Sunny','Terrano','Tiida','Titan','Z'],
 Honda:['CR-V','Civic','Accord','Fit','Vezel','HR-V','Odyssey','Pilot','Freed','Stepwgn','City','Clarity','Crosstour','CR-Z','e','Element','Insight','Integra','Jazz','Legend','N-Box','Passport','Prelude','Ridgeline','S2000','ZR-V'],
 Mazda:['CX-5','CX-9','CX-30','6','3','CX-50','CX-60','CX-8','CX-90','CX-3','2','5','323','626','929','Atenza','Axela','Biante','BT-50','CX-7','Demio','MPV','MX-5','Premacy','RX-7','RX-8','Tribute'],
 Mitsubishi:['Outlander','Pajero Sport','Pajero','ASX','Lancer','Eclipse Cross','Delica','L200','Xpander','Colt','Carisma','Dion','Eclipse','Galant','Grandis','i-MiEV','Mirage','Montero','RVR','Space Star'],
 'Land Rover':['Range Rover','Range Rover Sport','Defender','Discovery','Range Rover Velar','Range Rover Evoque','Discovery Sport','Freelander'],
 Volvo:['XC90','XC60','XC40','S90','S60','V60','V90','EX30','EX90','C40','C30','C70','EX40','S40','S80','V40','V50','V70','XC70'],
 Genesis:['GV80','GV70','G80','G70','G90','GV60','EQ900'],
 Infiniti:['QX80','QX60','QX50','Q50','QX70','Q60','FX','EX','G','M','JX','Q30','Q40','Q70','QX30','QX56'],
 Ford:['Explorer','Mustang','F-150','Focus','Mondeo','Kuga','Edge','Escape','Bronco','Expedition','C-Max','EcoSport','Escort','Everest','Fiesta','Flex','Fusion','Galaxy','Maverick','Puma','Ranger','S-Max','Taurus','Transit'],
 Chevrolet:['Tahoe','Camaro','Corvette','Suburban','Malibu','Traverse','Equinox','Cruze','Captiva','Trailblazer','Aveo','Blazer','Bolt','Cobalt','Colorado','Impala','Lacetti','Niva','Orlando','Silverado','Spark','Tracker','Trax'],
 Cadillac:['Escalade','XT5','XT6','CT5','XT4','CT4','CTS','SRX','Lyriq','ATS','BLS','CT6','DTS','Fleetwood','STS'],
 Tesla:['Model Y','Model 3','Model X','Model S','Cybertruck','Roadster'],
 BYD:['Song Plus','Tang','Han','Seal','Dolphin','Yuan Plus','Qin Plus','Seagull','Song L','Sealion 7','Atto 3','Destroyer 05','F3','Frigate 07','Qin','Seal U','Shark'],
 Exeed:['VX','TXL','LX','RX','Exlantix ES','Exlantix ET'],
 Tank:['300','500','400','700'],
 Voyah:['Free','Dream','Passion','Courage'],
 Avatr:['11','12','07','06'],
 Aito:['M9','M7','M5','M8'],
 Denza:['D9','N7','N8','Z9','Z9 GT'],
 Hongqi:['H9','HS5','H5','E-HS9','HS3','HQ9','H6','HS7','E-QM5','EH7'],
 GAC:['GS8','GS3','M8','Empow','GS5','GN8','GS4','Aion Y','Aion S','Aion V','Aion LX'],
 Jetour:['T2','Dashing','X70 Plus','X90 Plus','X70','X90','X50'],
 Jaecoo:['J7','J8','J6','J5'], Omoda:['C5','S5','S5 GT','E5','C7'],
 Skoda:['Kodiaq','Octavia','Superb','Karoq','Rapid','Fabia','Yeti','Kamiq','Scala','Enyaq','Citigo','Felicia','Roomster'],
 Renault:['Duster','Logan','Sandero','Arkana','Kaptur','Koleos','Megane','Fluence','Scenic','Clio','Austral','Espace','Kadjar','Kangoo','Laguna','Latitude','Talisman','Trafic','Twingo'],
 Peugeot:['3008','5008','408','308','2008','508','208','Partner','Traveller','206','107','207','301','307','4007','4008','407','Rifter'],
 Citroen:['C5 Aircross','C4','C3','C5','Berlingo','SpaceTourer','C4 Picasso','C3 Aircross','C-Elysee','C5 X','C1','C2','C6','DS3','DS4','DS5','Jumpy'],
 Opel:['Astra','Insignia','Mokka','Grandland','Zafira','Corsa','Antara','Crossland','Meriva','Vectra','Adam','Agila','Combo','Frontera','Omega','Vivaro'],
 Subaru:['Forester','Outback','XV','Crosstrek','Levorg','Impreza','Legacy','WRX','BRZ','Ascent','Exiga','Solterra','Tribeca'],
 Suzuki:['Jimny','Vitara','Grand Vitara','SX4','Swift','S-Cross','Solio','Ignis','Baleno','Alto','Escudo','Every','Hustler','Kizashi','Liana','Wagon R'],
 Jeep:['Grand Cherokee','Wrangler','Cherokee','Compass','Renegade','Gladiator','Wagoneer','Grand Wagoneer','Commander','Patriot','Liberty'],
 Dodge:['Challenger','Charger','Durango','Journey','Ram','Caliber','Caravan','Dart','Nitro','Viper','Avenger','Magnum'],
 RAM:['1500','2500','3500','ProMaster'], GMC:['Yukon','Sierra','Acadia','Terrain','Canyon','Hummer EV','Savana'],
 Buick:['Enclave','Envision','Encore','LaCrosse','Regal','GL8','Verano','Electra E5'],
 Lincoln:['Navigator','Aviator','Nautilus','Corsair','Continental','MKC','MKS','MKT','MKX','MKZ','Town Car'],
 MINI:['Cooper','Countryman','Clubman','Hatch','Cabrio','Paceman','Coupe','Roadster','Aceman'],
 Bentley:['Bentayga','Continental GT','Flying Spur','Mulsanne','Arnage','Azure','Brooklands'],
 'Rolls-Royce':['Cullinan','Ghost','Phantom','Wraith','Dawn','Spectre','Silver Shadow','Silver Spirit'],
 Lamborghini:['Urus','Huracan','Aventador','Revuelto','Gallardo','Murcielago','Diablo','Countach'],
 Ferrari:['Purosangue','Roma','Portofino','F8','296','SF90','812','488','458','California','F12','FF','GTC4Lusso'],
 Maserati:['Levante','Grecale','Ghibli','Quattroporte','GranTurismo','GranCabrio','MC20'],
 'Aston Martin':['DBX','DB11','DB12','Vantage','DBS','Rapide','DB9','Vanquish'],
 Acura:['MDX','RDX','TLX','ILX','Integra','NSX','TL','TSX','ZDX'],
 'Alfa Romeo':['Giulia','Stelvio','Tonale','Giulietta','159','147','156','Brera','MiTo','4C'],
 Fiat:['500','500X','500L','Panda','Tipo','Punto','Doblo','Ducato','Bravo','Freemont','Linea','Grande Punto'],
 SEAT:['Leon','Ateca','Ibiza','Tarraco','Arona','Alhambra','Altea','Toledo'],
 Cupra:['Formentor','Leon','Born','Ateca','Tavascan','Terramar'],
 Smart:['Fortwo','Forfour','#1','#3','#5','Roadster'],
 JAC:['JS4','JS6','JS3','J7','T6','T8','T9','S3','S5','iEV7S'],
 FAW:['Bestune T77','Bestune B70','Bestune T55','Bestune T99','Besturn X40','Besturn X80','Besturn B50','V5'],
 Dongfeng:['Aeolus Shine Max','580','AX7','DF6','E70','Huge','Mage'],
 ChanganDeepal:['S07','SL03','G318','S05'],
 BAIC:['X35','X55','X7','BJ40','BJ60','U5 Plus'],
 CheryExlantix:['ET','ES'],
 XPeng:['G6','G9','P7','P5','X9','G3'], NIO:['ES6','ES8','ET5','ET7','EC6','EC7','EL6','EL7','EL8'],
 Leapmotor:['C10','C11','C16','T03','B10','C01'],
 'Great Wall':['Poer','Poer KingKong','Wingle 7','Hover H3','Hover H5','Wingle 5','Safe'],
 Isuzu:['D-Max','MU-X','Trooper','Bighorn','Wizard'],
 SsangYong:['Rexton','Tivoli','Korando','Torres','Actyon','Kyron','Rodius','Musso'],
 Lada:['Vesta','Granta','Niva Travel','Niva Legend','Largus','XRAY','Priora','Kalina','2107','2114','2101','2104','2105','2106','2108','2109','2110','2111','2112'],
 UAZ:['Patriot','Pickup','Hunter','Profi','3151','3909','452','469'],
 'Москвич':['3','3e','6','8','2141','412'],
 Datsun:['on-DO','mi-DO','GO','GO+'], Daewoo:['Matiz','Nexia','Gentra','Lanos','Lacetti','Leganza','Nubira'],
 Saab:['9-3','9-5','900','9000','9-7X'], Hummer:['H2','H3','H1'],
 Daihatsu:['Tanto','Rocky','Move','Terios','Mira','Hijet','Copen','Cast','Wake','Thor'],
 Dacia:['Duster','Logan','Sandero','Jogger','Spring','Lodgy','Dokker'],
 MG:['ZS','HS','5','6','7','4','Cyberster','RX5'],
};
// Keep common import names under their own, recognizable manufacturer labels.
MODELS.Deepal=MODELS.ChanganDeepal;delete MODELS.ChanganDeepal;
MODELS.Exlantix=MODELS.CheryExlantix;delete MODELS.CheryExlantix;
const normalize=s=>String(s||'').trim().toLocaleLowerCase('ru');
const sort=(a,b)=>a.localeCompare(b,'ru',{numeric:true,sensitivity:'base'});
const unique=values=>[...new Map(values.filter(Boolean).map(v=>[normalize(v),v.trim()])).values()];
export function optionGroups(popular,all){const top=unique(popular).slice(0,10);const keys=new Set(top.map(normalize));return[{label:'Популярные',items:top},{label:'По алфавиту',items:unique(all).filter(x=>!keys.has(normalize(x))).sort(sort)}].filter(g=>g.items.length)}
export function brandGroups(cars=[]){return optionGroups(POPULAR_BRANDS,[...Object.keys(MODELS),...cars.map(c=>c.brand)])}
export function modelGroups(brand,cars=[]){const key=Object.keys(MODELS).find(k=>normalize(k)===normalize(brand));const list=MODELS[key]||[];return optionGroups(list.slice(0,10),[...list,...cars.filter(c=>normalize(c.brand)===normalize(brand)).map(c=>c.model)])}
export function canonicalBrand(value){return Object.keys(MODELS).find(k=>normalize(k)===normalize(value))||value.trim()}
