import {DocumentPreview as Preview} from './DocumentLink.jsx';
import React,{useState,useRef,useEffect} from 'react';
import {Upload,Trash2,Download,X,FileText} from 'lucide-react';
export default function VehicleDocuments({car,api,onUpdate,onDelete,readOnly}){
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[preview,setPreview]=useState(null);
 async function upload(type,e){const files=Array.from(e.target.files||[]);e.target.value='';if(!files.length)return;setBusy(true);setError('');let current=car;try{for(const file of files){if(!file.size||file.size>10*1024*1024)throw new Error('Файл должен быть непустым и не больше 10 МБ');const fd=new FormData();fd.set('file',file);fd.set('category',type==='UTILIZATION_RECEIPT'?'Чек':'Документ');fd.set('vehicleDocument',type);fd.set('revision',current.revision);fd.set('uploadId',crypto.randomUUID());current=await api('/cars/'+car.id+'/files',{method:'POST',body:fd});onUpdate(current)}}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function status(value,type='EPTS'){setBusy(true);setError('');try{onUpdate(await api('/cars/'+car.id+(type==='EPTS'?'/epts-status':'/utilization-status'),{method:'PATCH',body:{revision:car.revision,value}}))}catch(e){setError(e.message)}finally{setBusy(false)}}
 return <section className="panel vehicle-documents"><div className="panel-title"><h2>Документы автомобиля</h2></div><div className="payment-documents">{['TPO','EPTS','SBKTS','UTILIZATION_RECEIPT'].map(type=><div className="payment-document" style={['TPO','UTILIZATION_RECEIPT'].includes(type)?{gridColumn:'1 / -1'}:undefined} key={type}><div className="party-heading"><h3><FileText size={17}/> {type==='TPO'?'ТПО':type==='EPTS'?'ЭПТС':type==='SBKTS'?'СБКТС':'Утильсбор'}</h3>{!readOnly&&<label className="btn passport-choose"><Upload size={16}/> {busy?'Загрузка…':'Загрузить '+(type==='TPO'?'ТПО':type==='EPTS'?'ЭПТС':type==='SBKTS'?'СБКТС':'чек')}<input type="file" multiple accept=".pdf,.jpg,.jpeg,.png,.webp" disabled={busy} onChange={e=>upload(type,e)}/></label>}</div>{type==='EPTS'&&<div className="epts-status"><span className={'epts-dot '+(car.eptsStatus==='Действующий'?'valid':car.eptsStatus==='Недействующий'?'invalid':'')}/>{readOnly?<span>{car.eptsStatus||'Статус не указан'}</span>:<select aria-label="Статус ЭПТС" disabled={busy} value={car.eptsStatus||''} onChange={e=>status(e.target.value)}><option value="">Статус не указан</option><option>Действующий</option><option>Недействующий</option></select>}</div>}{type==='UTILIZATION_RECEIPT'&&<div className="epts-status"><span className={'epts-dot '+(car.utilizationStatus==='Оплачен'?'valid':'invalid')}/>{readOnly?<span>{car.utilizationStatus||'Не оплачен'}</span>:<select aria-label="Статус оплаты утильсбора" disabled={busy} value={car.utilizationStatus||'Не оплачен'} onChange={e=>status(e.target.value,type)}><option>Не оплачен</option><option>Оплачен</option></select>}</div>}{car.files.filter(f=>f.vehicleDocument===type).map(f=><div className="passport-saved-file" key={f.id}><button className="party-document-open" onClick={()=>setPreview(f)}>{f.name}</button><a className="icon-btn party-download" aria-label={'Скачать '+f.name} href={'/api/cars/'+car.id+'/files/'+f.id+'?download=1'} download={f.name}><Download size={16}/></a>{!readOnly&&<button className="icon-btn" aria-label={'Удалить '+f.name} disabled={busy} onClick={()=>onDelete(f)}><Trash2 size={16}/></button>}</div>)}{!car.files.some(f=>f.vehicleDocument===type)&&<p className="fine-print">Файлы пока не загружены</p>}</div>)}</div>{error&&<p className="error" role="alert">{error}</p>}{preview&&<Preview car={car} file={preview} onClose={()=>setPreview(null)}/>}</section>
}
