import {passwordLogin} from './password-login.js';
import {importCars} from './car-import.js';
import {encarRequest} from './encar-server.js';
import {assistantRequest} from './assistant-reader.js';
import {avitoRequest} from './avito-server.js';
import {telegramRequest} from './telegram-server.js';
import {intakeWebhook,intakeRequest} from './telegram-intake.js';
import {generateCarPhoto} from './photo-generation.js';
import {stageById,stageTimeline} from './route-stages.js';
import {saveLargeFile} from './large-file-save.js';
import {PAYER_TYPES,PAYMENT_METHODS,PAYMENT_DOCUMENTS} from './payment.js';
import {sessionIdentity,publicLogin} from './local-login.js';
import {identity,ensureAccess,membership,authorize,accessRequest} from './access.js';
import {fileResponse} from './file-response.js';
import {inventoryRequest} from './inventory.js';
import {basisInput,expenseRate} from './cost-basis.js';
import {publicationInput,snapshot,verifyCurrent,selectedCars,eligible,project,BOOM_ORIGIN} from './publication.js';
import {seedCars} from './seed.js';
import {recognizePassportAI} from './passport-ai-server.js';
import {generateContractDocx} from './contract-docx.js';
import {STATUSES,DOCUMENT_STATUSES,COST_TYPES,FILE_TYPES,PARTY_FIELDS,today,validDate,validateCar,validateParty} from './domain.js';
const uid=()=>crypto.randomUUID();
const json=(v,status=200)=>new Response(JSON.stringify(v),{status,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}});
class Problem extends Error{constructor(message,status=400){super(message);this.status=status}}
let initializing;
async function init(db){if(!db)throw new Problem('Облачная база недоступна. Повторите позже.',503);if(!initializing)initializing=(async()=>{
 await db.batch([db.prepare('CREATE TABLE IF NOT EXISTS inventory_backup_cars (backup_id TEXT NOT NULL,id TEXT NOT NULL,data TEXT NOT NULL,PRIMARY KEY(backup_id,id))'),db.prepare('CREATE TABLE IF NOT EXISTS cars (id TEXT PRIMARY KEY,vin TEXT UNIQUE NOT NULL,revision INTEGER NOT NULL,data TEXT NOT NULL)'),db.prepare('CREATE TABLE IF NOT EXISTS file_chunks (file_id TEXT NOT NULL,part INTEGER NOT NULL,data TEXT NOT NULL,PRIMARY KEY(file_id,part))'),db.prepare('CREATE TABLE IF NOT EXISTS app_meta (key TEXT PRIMARY KEY,value TEXT NOT NULL)')]);
 const seeded=await db.prepare("SELECT value FROM app_meta WHERE key='initialized'").first();
 if(!seeded){const cars=seedCars();await db.batch([...cars.map(c=>db.prepare('INSERT OR IGNORE INTO cars (id,vin,revision,data) VALUES (?,?,?,?)').bind(c.id,c.vin,1,JSON.stringify(c))),db.prepare("INSERT OR IGNORE INTO app_meta VALUES ('initialized','1')")])}
 })().catch(e=>{initializing=undefined;throw e});await initializing}
const recordEvent=(c,title,detail='',actor)=>{c.history.unshift({id:uid(),date:new Date().toISOString(),title,detail,actor});c.updatedAt=new Date().toISOString();c.lastWrite=uid()};
async function getCar(db,id){const row=await db.prepare('SELECT data FROM cars WHERE id=?').bind(id).first();if(!row)throw new Problem('Автомобиль не найден',404);return JSON.parse(row.data)}
async function body(req){try{return await req.json()}catch{throw new Problem('Не удалось прочитать данные')}}
// Legacy unique VIN column uses a reserved per-card key for missing VINs; public JSON keeps VIN empty.
const vinKey=c=>c.vin||'draft:'+c.id;
async function persist(db,c,rev,extra=[]){c.revision=rev+1;if(JSON.stringify(c).length>800000)throw new Problem('Карточка достигла предела размера. Сохраните резервную копию.');const stm=db.prepare('UPDATE cars SET vin=?,revision=?,data=? WHERE id=? AND revision=?').bind(vinKey(c),c.revision,JSON.stringify(c),c.id,rev);
 const result=await db.batch([stm,...extra]);if(!result[0].meta.changes)throw new Problem('Карточка изменена в другой вкладке. Обновите страницу и повторите.',409);return c}
function requireRevision(c,b){if(Number(b.revision)!==c.revision)throw new Problem('Карточка уже изменена. Обновите страницу и повторите.',409)}
function str(s,max=1000){return String(s||'').trim().slice(0,max)}
const fields=['customsCountry','documentStatus','owner','productionMonth','brand','model','trim','year','vin','color','status','location','country','price','mileage','purchaseDate','stockDate','soldDate','contact','notes'];
const fieldNames={customsCountry:'Таможня',documentStatus:'Статус документов',owner:'Собственник',productionMonth:'Месяц выпуска',brand:'Марка',model:'Модель',trim:'Комплектация',year:'Год',vin:'VIN',color:'Цвет',status:'Статус',location:'Местонахождение',country:'Страна вывоза',price:'Цена продажи',mileage:'Пробег',purchaseDate:'Дата покупки',stockDate:'Поступление на склад',soldDate:'Дата продажи',contact:'Контакт',notes:'Заметки'};
function carInput(b){const c={};for(const k of fields)c[k]=['year','price','mileage'].includes(k)&&(b[k]===null||b[k]===undefined||b[k]==='')?null:['year','price','mileage'].includes(k)?Number(b[k]||0):str(b[k],k==='notes'?5000:200);c.vin=c.vin.toUpperCase();c.status||='Не уточнён';c.documentStatus||='Нет';if(c.country==='Бишкек')c.customsCountry='Киргизия';const e=validateCar(c);if(e.length)throw new Problem(e.join('. '));return c}
function base64(bytes){const parts=[];for(let i=0;i<bytes.length;i+=32768)parts.push(String.fromCharCode(...bytes.subarray(i,i+32768)));return btoa(parts.join(''))}
function contractInput(b,c){
 if(!c.vin||!c.year)throw new Problem('Для договора дополните VIN и год выпуска автомобиля');
 const x={contractNo:str(b.contractNo,100),contractDate:str(b.contractDate,10),priceUsd:Number(b.priceUsd),priceRub:Number(b.priceRub),invoiceNo:str(b.invoiceNo,100),invoiceDate:str(b.invoiceDate,10)};
 if(!x.contractNo)throw new Problem('Укажите номер договора');if(!validDate(x.contractDate)||x.contractDate>today())throw new Problem('Проверьте дату договора');if(!x.invoiceNo)throw new Problem('Укажите номер инвойса');if(!validDate(x.invoiceDate)||x.invoiceDate>today())throw new Problem('Проверьте дату инвойса');
 if(!Number.isFinite(x.priceUsd)||x.priceUsd<=0||x.priceUsd>1e12)throw new Problem('Проверьте стоимость в долларах');if(!Number.isFinite(x.priceRub)||x.priceRub<=0||x.priceRub>1e15)throw new Problem('Проверьте стоимость в рублях');
 for(const [role,label] of [['seller','продавца'],['buyer','покупателя']]){const p=c[role];if(!p)throw new Problem(`Сначала добавьте ${label}`);const missing=[['fullName','ФИО'],['passportNumber','номер паспорта / ID'],['passportIssuedBy','кем выдан паспорт'],['passportIssueDate','дату выдачи паспорта'],['address','адрес регистрации']].filter(([k])=>!p[k]).map(([,name])=>name);if(missing.length)throw new Problem(`Дополните данные ${label}: ${missing.join(', ')}`)}
 return x;
}
export default {async fetch(req,env,ctx){const u=new URL(req.url);try{
 if(!u.pathname.startsWith('/api/')){const response=await env.ASSETS.fetch(req);if(response.headers.get('Content-Type')?.includes('text/html')){const headers=new Headers(response.headers);headers.set('Cache-Control','no-store');return new Response(response.body,{status:response.status,headers})}return response;}
 if(u.pathname==='/api/telegram/intake/webhook'&&req.method==='POST'){await init(env.DB);await ensureAccess(env.DB);return await intakeWebhook(req,env,ctx,{getCar,persist,event:(c,t,d)=>recordEvent(c,t,d,{name:'Владелец · Telegram',authMethod:'telegram-confirmed'})});}
 if(u.pathname==='/api/public/catalog'&&req.method==='GET'){await init(env.DB);const cars=(await selectedCars(env.DB)).map(c=>{const {revision,...safe}=c;return {...safe,videos:c.videos.map(v=>({url:u.origin+'/api/public/videos/'+encodeURIComponent(c.id)+'/'+encodeURIComponent(v.id),mime:v.mime})),photos:c.photos.map(p=>({url:u.origin+'/api/public/photos/'+encodeURIComponent(c.id)+'/'+encodeURIComponent(p.id)}))}});const r=json({cars,updatedAt:new Date().toISOString()});r.headers.set('Access-Control-Allow-Origin',BOOM_ORIGIN);return r;}
 const publicVideo=u.pathname.match(/^\/api\/public\/videos\/([^/]+)\/([^/]+)$/);
 if(publicVideo&&['GET','HEAD'].includes(req.method)){await init(env.DB);const c=await getCar(env.DB,decodeURIComponent(publicVideo[1]));const id=decodeURIComponent(publicVideo[2]);if(!eligible(c)||!project(c).videos.some(v=>v.id===id))throw new Problem('Видео не найдено',404);return fileResponse(req,env.DB,c.files.find(f=>f.id===id));}
 const publicPhoto=u.pathname.match(/^\/api\/public\/photos\/([^/]+)\/([^/]+)$/);
 if(publicPhoto&&['GET','HEAD'].includes(req.method)){await init(env.DB);const c=await getCar(env.DB,decodeURIComponent(publicPhoto[1]));const photoId=decodeURIComponent(publicPhoto[2]);if(!eligible(c)||!project(c).photos.some(p=>p.id===photoId))throw new Problem('Фото не найдено',404);return fileResponse(req,env.DB,c.files.find(f=>f.id===photoId));}
 if(!['GET','HEAD'].includes(req.method)){
 const origin=req.headers.get('Origin');if(origin&&origin!==u.origin)throw new Problem('Запрос с другого сайта отклонён',403);
 if(req.headers.get('Sec-Fetch-Site')==='cross-site')throw new Problem('Запрос с другого сайта отклонён',403);
 }
 await ensureAccess(env.DB);const passwordResponse=await passwordLogin(req,env.DB);if(passwordResponse)return passwordResponse;const loginResponse=await publicLogin(req,env.DB,env);if(loginResponse)return loginResponse;
 const actor=await sessionIdentity(req,env.DB)||identity(req);
 if(actor.authMethod==='link'&&!['GET','HEAD'].includes(req.method)&&req.headers.get('Origin')!==u.origin)throw new Problem('Запрос с другого сайта отклонён',403);
 if(u.pathname==='/api/session'||u.pathname.startsWith('/api/access/')){const response=await accessRequest(req,env,actor);if(response)return response;}
 authorize(await membership(env.DB,actor),req);
 const event=(c,title,detail='')=>recordEvent(c,title,detail,actor);
 if(u.pathname==='/api/passport/config'&&req.method==='GET')return json({enabled:!!env.OPENAI_API_KEY?.trim(),provider:'OpenAI'});
 if(u.pathname==='/api/passport/recognize'&&req.method==='POST')return json(await recognizePassportAI(req,env));
 await init(env.DB);const db=env.DB;
 if(u.pathname.startsWith('/api/encar/'))return await encarRequest(req,env,actor);
 if(u.pathname.startsWith('/api/assistant'))return await assistantRequest(req,env,actor,await membership(db,actor));
 if(u.pathname.startsWith('/api/telegram/intake'))return await intakeRequest(req,env,actor,await membership(db,actor),{getCar,persist,event});
 if(u.pathname.startsWith('/api/telegram/')||/^\/api\/cars\/[^/]+\/telegram(?:\/|$)/.test(u.pathname)){const response=await telegramRequest(req,env,actor,await membership(db,actor),{getCar,persist,event});if(response)return response;throw new Problem('Страница не найдена',404);}
 if(u.pathname.startsWith('/api/avito/')||/^\/api\/cars\/[^/]+\/avito(?:\/|$)/.test(u.pathname)){const response=await avitoRequest(req,env,actor,{getCar,persist,carInput,event});if(response)return response;throw new Problem('Страница не найдена',404);}
 if(u.pathname.startsWith('/api/inventory-')){const response=await inventoryRequest(req,db,b=>{const c={...carInput(b),costBasis:basisInput(b.costBasis),id:uid(),revision:1,isDemo:false,archived:false,costs:[],files:[],route:[],history:[],createdAt:new Date().toISOString()};event(c,'Импорт из таблицы', 'Собственник, VIN, автомобиль, месяц выпуска, стоимость до Бишкека и ТПО');return c});if(response)return response;}
 if(u.pathname==='/api/publication/snapshot'&&req.method==='POST')return json(await snapshot(db,env.BOOM_SYNC_SECRET));
 if(u.pathname==='/api/publication/verify'&&req.method==='POST')return json(await verifyCurrent(db,await body(req),env.BOOM_SYNC_SECRET));
 if(u.pathname==='/api/car-import'&&req.method==='POST')return await importCars(req,db,b=>{const c={...carInput(b),costBasis:basisInput(b.costBasis||{}),id:uid(),revision:1,isDemo:false,archived:false,costs:[],files:[],route:[],history:[],createdAt:new Date().toISOString()};event(c,'Импорт из таблицы',c.brand+' '+c.model+' · '+(c.vin||'VIN в заметках'));return c});
 if(u.pathname==='/api/cars'&&req.method==='GET'){const{results}=await db.prepare('SELECT data FROM cars ORDER BY json_extract(data,\'$.createdAt\') DESC').all();return json({cars:results.map(r=>JSON.parse(r.data)),storage:'cloud'})}
 if(u.pathname==='/api/cars'&&req.method==='POST'){const b=await body(req);const c={...carInput(b),costBasis:basisInput(b.costBasis||{}),id:uid(),revision:1,isDemo:false,archived:false,costs:[],files:[],route:[],history:[],createdAt:new Date().toISOString()};event(c,'Создана карточка',`${c.brand} ${c.model} · ${c.vin}`);c.route.push({id:uid(),date:today(),location:c.location,status:c.status,note:'Создание карточки',createdAt:c.createdAt});
 await db.prepare('INSERT INTO cars (id,vin,revision,data) VALUES (?,?,?,?)').bind(c.id,vinKey(c),1,JSON.stringify(c)).run();return json(c,201)}
 if(u.pathname==='/api/demo'&&req.method==='DELETE'){const b=await body(req);if(b.confirm!=='delete-demo')throw new Problem('Подтвердите удаление тестовых данных');const {results}=await db.prepare("SELECT data FROM cars WHERE json_extract(data,'$.isDemo')=1").all();const cs=results.map(r=>JSON.parse(r.data));await db.batch([...cs.flatMap(c=>c.files.map(f=>db.prepare('DELETE FROM file_chunks WHERE file_id=?').bind(f.id))),db.prepare("DELETE FROM cars WHERE json_extract(data,'$.isDemo')=1")]);return json({deleted:cs.length})}
 const m=u.pathname.match(/^\/api\/cars\/([^/]+)(?:\/(generate-photo|photo-order|cover|costs|route|files|archive|parties|contracts|publication|cost-basis|document-status|epts-status|utilization-status|payment)(?:\/([^/]+))?)?$/);if(!m)throw new Problem('Страница не найдена',404);
 const[,id,section,itemId]=m;let c=await getCar(db,id);
 if(!section&&req.method==='GET')return json(c);
 if(!section&&req.method==='DELETE'){const b=await body(req);requireRevision(c,b);if(b.confirm!=='delete-car')throw new Problem('Подтвердите удаление автомобиля');const result=await db.batch([db.prepare("DELETE FROM file_chunks WHERE file_id IN (SELECT json_extract(value,'$.id') FROM cars,json_each(cars.data,'$.files') WHERE cars.id=? AND cars.revision=?)").bind(c.id,c.revision),db.prepare('DELETE FROM cars WHERE id=? AND revision=?').bind(c.id,c.revision)]);if(!result[1].meta.changes)throw new Problem('Карточка уже изменилась. Обновите страницу.',409);return json({deleted:c.id});}

 if(section==='generate-photo'&&req.method==='POST')return json(await generateCarPhoto(req,env,c,await body(req))); 
 if(section==='files'&&itemId&&['GET','HEAD'].includes(req.method)){const f=c.files.find(x=>x.id===itemId);if(!f)throw new Problem('Файл не найден',404);return await fileResponse(req,db,f)}
 if(section==='contracts'&&!itemId&&req.method==='POST'){
  const b=await body(req);requireRevision(c,b);const rev=c.revision,data=contractInput(b,c);const bytes=generateContractDocx({car:c,seller:c.seller,buyer:c.buyer,...data});
  const safe=(c.buyer.fullName.split(/\s+/)[0]||'покупатель').replace(/[^\p{L}\p{N}_-]+/gu,'_');const f={id:uid(),name:str(`ДКП_${safe}_${c.brand}_${c.model}_${data.contractDate}.docx`,240),mime:'application/vnd.openxmlformats-officedocument.wordprocessingml.document',size:bytes.length,category:'Договор',contract:data,date:new Date().toISOString()};c.files.push(f);event(c,'Сгенерирован договор',`${f.name}\nИнвойс № ${data.invoiceNo} от ${data.invoiceDate}`);
  const encoded=base64(bytes),extra=[];for(let i=0;i<encoded.length;i+=240000)extra.push(db.prepare('INSERT INTO file_chunks (file_id,part,data) SELECT ?,?,? WHERE EXISTS(SELECT 1 FROM cars WHERE id=? AND revision=? AND json_extract(data,\'$.lastWrite\')=?)').bind(f.id,i/240000,encoded.slice(i,i+240000),c.id,rev+1,c.lastWrite));const saved=await persist(db,c,rev,extra);return json({car:saved,file:f});
 }
 if(section==='files'&&!itemId&&req.method==='POST'){
 if(Number(req.headers.get('Content-Length')||0)>31*1024*1024)throw new Problem('Размер видео — не более 30 МБ');const fd=await req.formData();const file=fd.get('file');const category=String(fd.get('category'));const vehicleDocument=String(fd.get('vehicleDocument')||'');if(vehicleDocument&&(!['TPO','EPTS','SBKTS','UTILIZATION_RECEIPT'].includes(vehicleDocument)||category!==(vehicleDocument==='UTILIZATION_RECEIPT'?'Чек':'Документ')))throw new Problem('Выберите ТПО, ЭПТС, СБКТС или чек утильсбора');const paymentDocument=String(fd.get('paymentDocument')||'');if(paymentDocument&&(!PAYMENT_DOCUMENTS.includes(paymentDocument)||!['Договор','Документ'].includes(category)))throw new Problem('Выберите тип документа по оплате');const uploadId=String(fd.get('uploadId')||'');if(uploadId&&!/^[0-9a-f-]{36}$/.test(uploadId))throw new Problem('Неверный идентификатор загрузки');if(uploadId&&c.files.some(f=>f.id===uploadId))return json(c);requireRevision(c,{revision:fd.get('revision')});if(!file||typeof file==='string'||!file.size)throw new Problem('Выберите непустой файл');if(file.size>(category==='Видео'?30:10)*1024*1024)throw new Problem(category==='Видео'?'Видео — не более 30 МБ':'Файл — не более 10 МБ');if(!FILE_TYPES.includes(category))throw new Problem('Выберите категорию файла');
 const allowed={'mp4':'video/mp4','mov':'video/quicktime','webm':'video/webm','jpg':'image/jpeg','jpeg':'image/jpeg','png':'image/png','webp':'image/webp','pdf':'application/pdf','doc':'application/msword','docx':'application/vnd.openxmlformats-officedocument.wordprocessingml.document','xls':'application/vnd.ms-excel','xlsx':'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','txt':'text/plain','csv':'text/csv'};const ext=file.name.split('.').pop().toLowerCase();if(!allowed[ext])throw new Problem('Поддерживаются JPG, PNG, WEBP, PDF, Word, Excel, TXT и CSV');if(category==='Фото'&&!['jpg','jpeg','png','webp'].includes(ext))throw new Problem('Для фото выберите JPG, PNG или WEBP');
 const videoExt=['mp4','mov','webm'].includes(ext);if((category==='Видео')!==videoExt)throw new Problem('Видео добавляется только через «Добавить видео»');
 const bytes=new Uint8Array(await file.arrayBuffer());if(category==='Видео'){const tag=String.fromCharCode(...bytes.slice(4,8));const ok=ext==='webm'?bytes[0]===0x1a&&bytes[1]===0x45&&bytes[2]===0xdf&&bytes[3]===0xa3:bytes.length>=12&&(tag==='ftyp'||(ext==='mov'&&['moov','mdat','wide'].includes(tag)));if(!ok)throw new Problem('Файл не соответствует формату видео')}if(category==='Фото'){const ok=ext==='png'?bytes[0]===137&&bytes[1]===80&&bytes[2]===78:ext==='webp'?String.fromCharCode(...bytes.slice(0,4))==='RIFF'&&String.fromCharCode(...bytes.slice(8,12))==='WEBP':bytes[0]===255&&bytes[1]===216;if(!ok)throw new Problem('Содержимое не соответствует формату изображения')}
 const rev=c.revision;const f={id:uploadId||uid(),name:str(file.name,240),mime:allowed[ext],size:file.size,category,...(vehicleDocument?{vehicleDocument}:{}),...(paymentDocument?{paymentDocument}:{}),date:new Date().toISOString()};c.files.push(f);event(c,paymentDocument?'Добавлен документ по оплате':'Добавлен файл',`${paymentDocument||category}: ${f.name}`);if(bytes.length>4*1024*1024)return json(await saveLargeFile(db,c,rev,f.id,bytes,base64,persist));const encoded=base64(bytes);const extra=[];for(let i=0;i<encoded.length;i+=240000)extra.push(db.prepare('INSERT INTO file_chunks (file_id,part,data) SELECT ?,?,? WHERE EXISTS(SELECT 1 FROM cars WHERE id=? AND revision=? AND json_extract(data,\'$.lastWrite\')=?)').bind(f.id,i/240000,encoded.slice(i,i+240000),c.id,rev+1,c.lastWrite));return json(await persist(db,c,rev,extra));
 }
 let b;let passportFiles=[];
 if(section==='parties'&&req.method==='PATCH'&&req.headers.get('Content-Type')?.startsWith('multipart/form-data')){
  if(!['seller','buyer'].includes(itemId))throw new Problem('Выберите покупателя или продавца');
  if(Number(req.headers.get('Content-Length')||0)>11*1024*1024)throw new Problem('Общий размер фотографий — до 10 МБ');
  const fd=await req.formData();let party;try{party=JSON.parse(fd.get('party'))}catch{throw new Problem('Не удалось прочитать данные продавца')}
  passportFiles=fd.getAll('passport');
  if(!passportFiles.length||passportFiles.length>3||passportFiles.some(f=>typeof f==='string'||!f.size)||passportFiles.reduce((n,f)=>n+f.size,0)>10*1024*1024)throw new Problem('Выберите до 3 фото паспорта, суммарно до 10 МБ');
  b={party,passportOnly:fd.get('passportOnly')==='true',revision:fd.get('revision')};
 }else b=await body(req);
 requireRevision(c,b);const rev=c.revision;
 if(section==='payment'&&req.method==='PATCH'){const p=b.payment;if(!p||!['',...PAYER_TYPES].includes(p.payerType)||!['',...PAYMENT_METHODS].includes(p.method))throw new Problem('Выберите плательщика и способ оплаты из списка');const amount=p.contractAmountRub===undefined?c.payment?.contractAmountRub:p.contractAmountRub;const contractAmountRub=amount===undefined||amount===null||amount===''?null:Number(amount);if(contractAmountRub!==null&&(!Number.isFinite(contractAmountRub)||contractAmountRub<0||contractAmountRub>1e12))throw new Problem('Проверьте сумму в договоре');const next={payerType:p.payerType,method:p.method,contractAmountRub};if(JSON.stringify(c.payment||{payerType:'',method:''})===JSON.stringify(next))return json(c);event(c,'Изменены параметры оплаты',JSON.stringify({before:c.payment||{},after:next}));c.payment=next;return json(await persist(db,c,rev))}
 if(section==='photo-order'&&req.method==='PATCH'){const photos=c.files.filter(f=>f.category==='Фото'&&!f.partyRole);const i=photos.findIndex(f=>f.id===b.fileId);if(i<0||![-1,1].includes(b.direction))throw new Problem('Выберите фото и направление');const j=i+b.direction;if(j<0||j>=photos.length)return json(c);[photos[i],photos[j]]=[photos[j],photos[i]];let k=0;c.files=c.files.map(f=>f.category==='Фото'&&!f.partyRole?photos[k++]:f);event(c,'Изменён порядок фотографий',photos[j].name);return json(await persist(db,c,rev))}
 if(section==='cover'&&req.method==='PATCH'){const photo=c.files.find(f=>f.id===b.fileId&&f.category==='Фото'&&!f.partyRole);if(!photo)throw new Problem('Фотография не найдена',404);c.files=[photo,...c.files.filter(f=>f.id!==photo.id)];event(c,'Изменена обложка автомобиля',photo.name);return json(await persist(db,c,rev))}
 if(section==='utilization-status'&&req.method==='PATCH'){if(!['Оплачен','Не оплачен'].includes(b.value))throw new Problem('Выберите статус оплаты утильсбора');if((c.utilizationStatus||'Не оплачен')===b.value)return json(c);event(c,'Изменён статус оплаты утильсбора',(c.utilizationStatus||'Не оплачен')+' → '+b.value);c.utilizationStatus=b.value;if(c.costBasis?.expenses?.recyclingRub)c.costBasis.expenses.recyclingRub.paid=b.value==='Оплачен';return json(await persist(db,c,rev))}
 if(section==='epts-status'&&req.method==='PATCH'){if(!['','Действующий','Недействующий'].includes(b.value))throw new Problem('Выберите статус ЭПТС');event(c,'Изменён статус ЭПТС',(c.eptsStatus||'Не указан')+' → '+(b.value||'Не указан'));c.eptsStatus=b.value;return json(await persist(db,c,rev))}
 if(section==='document-status'&&req.method==='PATCH'){if(!DOCUMENT_STATUSES.includes(b.value))throw new Problem('Выберите статус документов');if((c.documentStatus||'Нет')===b.value)return json(c);event(c,'Изменён статус документов',(c.documentStatus||'Нет')+' → '+b.value);c.documentStatus=b.value;return json(await persist(db,c,rev))}
 if(section==='cost-basis'&&req.method==='PATCH'){const next=basisInput({...b.values,expenses:b.values?.expenses??c.costBasis?.expenses});if(next.expenses?.recyclingRub) c.utilizationStatus=next.expenses.recyclingRub.paid?'Оплачен':'Не оплачен';event(c,'Обновлена себестоимость',JSON.stringify({before:c.costBasis||{},after:next}));c.costBasis=next;return json(await persist(db,c,rev))}
 if(section==='publication'&&req.method==='PATCH'){c.publication=publicationInput(c,b);event(c,'Обновлено объявление Бум Авто',c.publication.enabled?'Выбран для следующей выгрузки на сайт':'Исключён из следующей выгрузки');return json(await persist(db,c,rev))}
 if(section==='parties'&&req.method==='PATCH'){
  if(!['buyer','seller'].includes(itemId))throw new Problem('Выберите покупателя или продавца',400);
  if(!b.party||typeof b.party!=='object'||Array.isArray(b.party))throw new Problem('Заполните данные покупателя или продавца');
  const party={};for(const [key] of PARTY_FIELDS)party[key]=String(b.party[key]??'').trim();
  const errors=b.passportOnly?[]:validateParty(party);if(errors.length)throw new Problem(errors.join('. '));
  const old=c[itemId];const changed=b.passportOnly?[]:PARTY_FIELDS.filter(([key])=>(old?.[key]||'')!==party[key]);
  if(!changed.length&&!passportFiles.length)return json(c);
  if(!b.passportOnly)c[itemId]={...party,updatedAt:new Date().toISOString()};
  if(changed.length)event(c,old?(itemId==='buyer'?'Обновлены данные покупателя':'Обновлены данные продавца'):(itemId==='buyer'?'Добавлен покупатель':'Добавлен продавец'),changed.map(([key,label])=>`${label}: ${old?.[key]||'—'} → ${party[key]||'—'}`).join('\n'));
  const prepared=[];
  for(const file of passportFiles){
   const ext=file.name.split('.').pop().toLowerCase();const mime={jpg:'image/jpeg',jpeg:'image/jpeg',png:'image/png',webp:'image/webp',pdf:'application/pdf'}[ext];
   if(!mime||file.type!==mime)throw new Problem('Паспорт: поддерживаются JPG, PNG, WEBP и PDF');
   const bytes=new Uint8Array(await file.arrayBuffer());const signature=mime==='application/pdf'?String.fromCharCode(...bytes.slice(0,5))==='%PDF-':mime==='image/jpeg'?bytes[0]===255&&bytes[1]===216:mime==='image/png'?bytes[0]===137&&bytes[1]===80&&bytes[2]===78:String.fromCharCode(...bytes.slice(0,4))==='RIFF'&&String.fromCharCode(...bytes.slice(8,12))==='WEBP';
   if(!signature)throw new Problem('Содержимое файла не соответствует формату изображения');
   const f={id:uid(),name:str('Паспорт '+(itemId==='buyer'?'покупателя':'продавца')+' — '+file.name,240),mime,size:file.size,category:'Документ',partyRole:itemId,date:new Date().toISOString()};c.files.push(f);prepared.push({id:f.id,encoded:base64(bytes)});event(c,'Добавлен паспорт '+(itemId==='buyer'?'покупателя':'продавца'),f.name);
  }
  const extra=[];for(const f of prepared)for(let i=0;i<f.encoded.length;i+=240000)extra.push(db.prepare('INSERT INTO file_chunks (file_id,part,data) SELECT ?,?,? WHERE EXISTS(SELECT 1 FROM cars WHERE id=? AND revision=? AND json_extract(data,\'$.lastWrite\')=?)').bind(f.id,i/240000,f.encoded.slice(i,i+240000),c.id,rev+1,c.lastWrite));
  return json(await persist(db,c,rev,extra));
 }
 if(!section&&req.method==='PATCH'){const next=carInput({...c,...b});const nextBasis=b.costBasis!==undefined?basisInput(b.costBasis):c.costBasis;const changes=fields.filter(k=>c[k]!==next[k]).map(k=>`${fieldNames[k]}: ${c[k]||'—'} → ${next[k]||'—'}`);if(JSON.stringify(nextBasis)!==JSON.stringify(c.costBasis))changes.push('Обновлены стоимость и курсы автомобиля');if(!changes.length)return json(c);c.costBasis=nextBasis;if(c.status!==next.status||c.location!==next.location)c.route.push({id:uid(),date:today(),location:next.location,status:next.status,note:'Изменено в карточке',createdAt:new Date().toISOString()});Object.assign(c,next);event(c,'Обновлена карточка',changes.join('\n'));return json(await persist(db,c,rev))}
 if(section==='archive'&&req.method==='POST'){c.archived=!!b.archived;event(c,c.archived?'Автомобиль перемещён в архив':'Автомобиль восстановлен из архива');return json(await persist(db,c,rev))}
 if(section==='costs'&&(req.method==='POST'||req.method==='PATCH')){
 const old=itemId?c.costs.find(x=>x.id===itemId):null;if(itemId&&!old)throw new Problem('Расход не найден',404);
 const input={...old,...b};const rate=expenseRate(c,input);if(!COST_TYPES.includes(input.type)||!validDate(input.date)||!['RUB','USD','EUR','CNY','AED'].includes(input.currency)||!Number.isFinite(Number(input.amount))||Number(input.amount)<=0||Number(input.amount)>1e10||!Number.isFinite(rate)||rate<=0||rate>1e6||input.paid!==undefined&&typeof input.paid!=='boolean')throw new Problem('Проверьте статью, дату, сумму, валюту и курс');
 const v={id:itemId||uid(),type:input.type,description:str(input.description),date:input.date,amount:Math.round(Number(input.amount)*100)/100,currency:input.currency,rate:input.currency==='RUB'?1:(input.rate===null||input.rate===undefined||input.rate==='')?null:Number(input.rate),paid:input.paid===true};
 if(old){c.costs[c.costs.findIndex(x=>x.id===itemId)]=v;event(c,'Изменён расход',JSON.stringify({before:old,after:v}));}else{c.costs.push(v);event(c,'Добавлен расход',`${v.type}: ${v.amount} ${v.currency} · курс ${rate} · ${v.paid?'оплачен':'не оплачен'}`);}return json(await persist(db,c,rev));}

 if(section==='costs'&&itemId&&req.method==='DELETE'){const f=c.costs.find(x=>x.id===itemId);if(!f)throw new Problem('Расход не найден',404);c.costs=c.costs.filter(x=>x.id!==itemId);event(c,'Удалён расход',`${f.type}: ${f.amount} ${f.currency} · курс ${f.rate}`);return json(await persist(db,c,rev))}
 if(section==='route'&&(req.method==='POST'||req.method==='PATCH')){const old=itemId?c.route.find(r=>r.id===itemId):null;if(req.method==='PATCH'&&(!old||!old.stage))throw new Problem('Этап не найден',404);if(req.method==='PATCH'&&!stageById(b.stage))throw new Problem('Выберите этап из списка');const previousArrival=stageTimeline(c.route).find(r=>r.stage==='arrived_voronezh');if(b.stage!==undefined){const stage=stageById(b.stage);if(!stage)throw new Problem('Выберите этап из списка');b.status=stage.status;b.location=stage.location||c.country||c.location||'Место не указано';}if(!validDate(b.date)||b.date>today()||!STATUSES.includes(b.status)||!str(b.location))throw new Problem('Укажите этап и дату не позднее сегодняшней');const r={id:old?.id||uid(),...(b.stage?{stage:b.stage}:{}),date:b.date,status:b.status,location:str(b.location,200),note:str(b.note??old?.note),createdAt:old?.createdAt||new Date().toISOString()};if(old)c.route[c.route.findIndex(x=>x.id===old.id)]=r;else c.route.push(r);c.route.sort((a,b)=>a.date.localeCompare(b.date)||a.createdAt.localeCompare(b.createdAt));const latest=b.stage?stageTimeline(c.route).at(-1):c.route.at(-1);if(old||latest.id===r.id){c.status=latest.status;c.location=latest.location;if(['Прибыл','На складе'].includes(c.status)&&!c.stockDate)c.stockDate=latest.date;if(old&&previousArrival&&c.stockDate===previousArrival.date)c.stockDate=stageTimeline(c.route).find(x=>x.stage==='arrived_voronezh')?.date||'';if(c.status==='Продан')c.soldDate=r.date;else c.soldDate='';const errors=validateCar(c);if(errors.length)throw new Problem(errors.join('. '))}event(c,old?'Изменён этап маршрута':'Добавлен этап маршрута',(old?`Было: ${old.date} · ${stageById(old.stage)?.label||old.status}\nСтало: `:'')+`${r.date} · ${stageById(r.stage)?.label||r.status} · ${r.location}${r.note?' · '+r.note:''}`);return json(await persist(db,c,rev))}
 if(section==='files'&&itemId&&req.method==='DELETE'){const f=c.files.find(x=>x.id===itemId);if(!f)throw new Problem('Файл не найден',404);c.files=c.files.filter(x=>x.id!==itemId);if(c.publication){c.publication.photoIds=(c.publication.photoIds||[]).filter(x=>x!==itemId);c.publication.videoIds=(c.publication.videoIds||[]).filter(x=>x!==itemId);}event(c,'Удалён файл',f.name);return json(await persist(db,c,rev,[db.prepare('DELETE FROM file_chunks WHERE file_id=? AND EXISTS(SELECT 1 FROM cars WHERE id=? AND revision=? AND json_extract(data,\'$.lastWrite\')=?)').bind(f.id,c.id,rev+1,c.lastWrite)]))}
 throw new Problem('Действие не поддерживается',405);
 }catch(e){if(String(e.message).includes('UNIQUE constraint failed: cars.vin'))return json({error:'Автомобиль с таким VIN уже существует, в том числе в архиве.'},409);if(!e.status)console.error('API error',e.message);return json({error:e.status?e.message:'Не удалось сохранить данные. Обновите страницу и повторите.'},e.status||500)}}};
